(function(g){var window=this;'use strict';var iXH=async function(f){if(f.S)try{await f.S.promise}catch{}},zsI=async function(f,k,G){f.K=g.aE(k,G)},CoW=async function(f,k,G,t){try{let Z=f.C;
if(f.yG.X().Y("html5_await_track_decoration_in_load_track")&&(await iXH(f),f.xj()||f.C!==Z))return;let u=f.V(k,G),h=f.yG.X().Y("html5_report_captions_ctmp_qoe"),W=(0,g.S)();await zsI(f,u,{format:"RAW",onSuccess:D=>{if(f.K){f.K=null;if(h){var V=(D.responseText.length/1024).toFixed();let U=(0,g.S)();f.videoData.Wz("capresp",{ms:U-W,kb:V})}V=D.getResponseHeader&&D.getResponseHeader("Content-Length")?Number(D.getResponseHeader("Content-Length")):0;t.fF(D.responseText,k,void 0,void 0,V)}},
onError:h?D=>{f.videoData.Wz("capfail",{status:D?.status??0})}:void 0,
withCredentials:!0})}catch{}},o2=function(f){f.isActive()||f.start()},ESY=function(f,k){var G=new g.kx;
G.languageCode=f.languageCode;G.languageName=f.languageName;G.name=f.name;G.displayName=f.displayName;G.kind=f.kind;G.isDefault=!1;G.B=f.B;G.isTranslateable=f.isTranslateable;G.vssId=f.vssId;G.url=f.url;G.translationLanguage=k;f.xtags&&(G.xtags=f.xtags);f.captionId&&(G.captionId=f.captionId);return G},Wd=function(f,k){return k?f.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},m2A=function(f){return g.Fp(f)||f.Y("web_enable_caption_language_preference_stickiness")},nSC=async function(f,k){f=
f+"|"+k;
k=await g.hz();if(!k)throw g.s3("gct");return(await g.tf(k)).get("captions",f)},LrI=function(f,k,G){nSC(f,k).then(t=>{t&&G(t.trackData,new g.kx(t.metadata))})},Di=function(f){if(!d26.test(f))throw Error("'"+f+"' is not a valid hex color");
f.length==4&&(f=f.replace(sup,"#$1$1$2$2$3$3"));f=f.toLowerCase();f=parseInt(f.slice(1),16);return[f>>16,f>>8&255,f&255]},bXi=function(){var f={},k="suggest_correction"in g.y8?g.y8.suggest_correction:"Edit caption";
k=k||"";for(let G in f){let t=()=>String(f[G]);
k=k.replace(new RegExp("\\$\\{"+G+"\\}","gi"),t);k=k.replace(new RegExp("\\$"+G,"gi"),t)}return k},Vr=function(){return g.k9("yt-player-caption-display-settings")},wMH=function(f,k){var G=g.On(f.segments,k);
G>=0||G<0&&(-G-1)%2===1||(G=-G-1,G>0&&k-f.segments[G-1]===1&&G<f.segments.length&&f.segments[G]-k===1?(g.op(f.segments,G),g.op(f.segments,G-1)):G>0&&k-f.segments[G-1]===1?f.segments[G-1]=k:G<f.segments.length&&f.segments[G]-k===1?f.segments[G]=k:(g.ea(f.segments,G,0,k),g.ea(f.segments,G+1,0,k)))},a1a=function(f){return f.B&&f.B.Z?f.B.Z+f.player.jj()<f.player.getCurrentTime():!1},rta=function(f,k){if(f.policy.jQ&&f.player.J_()){var G=g.aC(k,f.policy,{});
G.set("pot",f.player.J_());G=G.sN()}else G=g.aC(k,f.policy,{}).sN();var t={format:"RAW",withCredentials:!0};if(f.policy.ME){t.method="POST";let h=k.S;h&&Object.keys(h).length>0?t.postBody=g.l4(h,g.Z8):t.postBody=(0,g.Nr)([120,0])}f.Z&&(t.responseType="arraybuffer");var Z=++f.S6,u=(0,g.S)();f.K=g.S3(G,t,3,100,-1,h=>{h.errorCode==="net.timeout"&&f.player.Wz("capnt",{rn:Z++})}).then(h=>{if(f.policy.IN&&Z%100===1){var W=(0,g.S)();
f.player.Wz("caprsp",{rn:Z,ms:W-u,kb:(h.xhr.responseText.length/1024).toFixed()})}a:{h=h.xhr;f.xj();if(f.W){var D=!(f.Z?h.response:h.responseText)||h.status>=400;if(W=g.HcE(h)){h=g.aC(f.W,f.policy,{});f.W.lf(h,W);rta(f,f.W);break a}D?f.player.Wz("capfail",{status:h.status}):(g.eX("fcb_r",(0,g.S)(),f.player.getVideoData().QP||""),W=f.W.f7[0],D=W.wH,f.C!=null&&f.A!==D&&(f.Z?f.C(h.response,(W.segmentStartTime+f.player.jj())*1E3):f.C(h.responseText,(W.segmentStartTime+f.player.jj())*1E3),f.A=D))}f.W=
null;f.K=null}}).Xr(h=>{f.W=null;
f.K=null;f.player.Wz("capfail",{rn:Z,status:h.xhr?.status})});
f.W=k;wMH(f.S,f.W.f7[0].wH)},MHe=function(f,k){return k!=null&&k in f.K.B?f.K.B[k]:null},HXM=function(f,k,G){var t=[];
for(let Z in f.K.B){if(!f.K.B.hasOwnProperty(Z))continue;let u=f.K.B[Z];if(g.pj(u,G||null)){let h=u.info.captionTrack;h&&h.languageCode===k&&t.push(u)}}return t.length?t[0]:null},x2n=function(f,k){var G=[];
for(let Z in f.K.B){if(!f.K.B.hasOwnProperty(Z))continue;var t=f.K.B[Z];if(g.pj(t,k||null)){let u=t.info.id,h=u,W=`.${u}`,D="",V="";if(t=t.info.captionTrack)u=t.languageCode,h=t.displayName,W=t.vssId,D=t.kind,V=t.id;G.push(new g.kx({id:Z,languageCode:u,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:W,kind:D,captionId:V}))}}return G},XMW=function(f,k,G,t){var Z=k/360*16;
k>=f&&(f=640,t>G*1.3&&(f=480),Z=G/f*16);return Z},l1M=function(f){var k=1+.25*(f.fontSizeIncrement||0);
if(f.offset===0||f.offset===2)k*=.8;return k},ThW=function(f,k){var G="vertical-rl";
f.B.IT===1&&(G="vertical-lr");g.lD&&(G=G==="vertical-lr"?"tb-lr":"tb-rl");g.X3(k,"-o-writing-mode",G);g.X3(k,"-webkit-writing-mode",G);g.X3(k,"writing-mode",G);g.X3(k,"text-orientation","upright");g.bD(k,"ytp-vertical-caption");f.K.params.RL===3&&(g.X3(k,"text-orientation",""),g.X3(k,"transform","rotate(180deg)"))},SBM=function(f,k){var G={},t=k.background?k.background:f.B.PO.background;
if(k.backgroundOpacity!=null||k.background){var Z=k.backgroundOpacity!=null?k.backgroundOpacity:f.B.PO.backgroundOpacity;t=Di(t);G.background="rgba("+t[0]+","+t[1]+","+t[2]+","+Z+")";f.j6&&(G["box-decoration-break"]="clone",G["border-radius"]=`${f.Ee*.25}px`)}if(k.fontSizeIncrement!=null||k.offset!=null)G["font-size"]=`${f.cz*l1M(k)}px`;f.experiments.rH("enable_player_captions_new_style_defaults")&&(G["line-height"]="1.375");t=1;Z=k.color||f.B.PO.color;if(k.color||k.textOpacity!=null)Z=Di(Z),t=k.textOpacity==
null?f.B.PO.textOpacity:k.textOpacity,Z="rgba("+Z[0]+","+Z[1]+","+Z[2]+","+t+")",G.color=Z,G.fill=Z;var u=k.charEdgeStyle;u===0&&(u=void 0);if(u){Z=`rgba(34, 34, 34, ${t})`;let D=`rgba(204, 204, 204, ${t})`;k.Q7&&(D=Z=k.Q7);let V=f.cz/16/2,U=Math.max(V,1);var h=Math.max(2*V,1),W=Math.max(3*V,1);let e=Math.max(5*V,1);t=[];switch(u){case 4:for(;W<=e;W+=V)t.push(`${h}px ${h}px ${W}px ${Z}`);break;case 1:h=window.devicePixelRatio>=2?.5:1;for(u=U;u<=W;u+=h)t.push(`${u}px ${u}px ${Z}`);break;case 2:t.push(`${U}px ${U}px ${D}`);
t.push(`-${U}px -${U}px ${Z}`);break;case 3:for(W=0;W<5;W++)t.push(`0 0 ${h}px ${Z}`)}G["text-shadow"]=t.join(", ")}Z="";switch(k.fontFamily){case 1:Z='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", serif-monospace, monospace';break;case 2:Z='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:Z='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", sans-serif-monospace, monospace';break;case 5:Z='"Comic Sans MS", Impact, Handlee, fantasy';break;
case 6:Z='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:Z=g.vf()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:Z='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}Z&&(G["font-family"]=Z);Z=k.offset;Z==null&&(Z=f.B.PO.offset);switch(Z){case 0:G["vertical-align"]="sub";break;case 2:G["vertical-align"]="super"}k.fontFamily===7&&(G["font-variant"]=
"small-caps");k.bold&&(G["font-weight"]="bold");k.italic&&(G["font-style"]="italic");k.underline&&(G["text-decoration"]="underline");k.QF&&(G.visibility="hidden");k.Qd===1&&f.S&&(G["text-combine-upright"]="all",G["text-orientation"]="mixed",Z=g.Ch||g.na,f.K.params.RL===3?G.transform=Z?"rotate(90deg)":"rotate(180deg)":Z&&(G.transform="rotate(-90deg)"));if(k.textEmphasis===1||k.textEmphasis===2||k.textEmphasis===3||k.textEmphasis===4||k.textEmphasis===5)if(g.Ch)G["font-weight"]="bold";else switch(G["text-emphasis-style"]=
"filled circle",G["text-emphasis-color"]="currentcolor",G["webkit-text-emphasis"]="filled circle",k.textEmphasis){case 4:case 3:G["text-emphasis-position"]="under left";G["webkit-text-emphasis-position"]="under left";break;case 5:case 2:G["text-emphasis-position"]="over right",G["webkit-text-emphasis-position"]="over right"}return G},Rss=function(f,k){if(f.NE&&k.length===0)return 0;
f=1;for(let G=0;G<k.length;G++){let t=k[G];typeof t.text==="string"&&(f+=t.text.split("\n").length-1,t.append||G===0||f++)}return f},vd=function(f){f=f.split("px");
return f.length>0?(f=Number(f[0]))?f:0:0},gSn=function(f,k,G){f.ME=f.ME||!!G;
var t={};Object.assign(t,f.B.PO);Object.assign(t,G||k.B);Object.assign(t,f.Jh.PO);f.Oe&&(t.backgroundOpacity=0);(G=!f.Z)&&cte(f);var Z=f.Yj&&f.FL&&g.TK(t,f.FL)?f.Yj:pMs(f,t),u=typeof k.text==="string",h=u?k.text.split("\n"):[k.text];for(let D=0;D<h.length;D++){var W=D>0||!k.append;let V=h[D];W&&!G?(cte(f),Z=pMs(f,t)):W&&G&&(G=!1);V&&(Z.appendChild(u?g.WS(V):V),u||V.tagName!=="RUBY"||V.childElementCount!==4||g.Ch||!g.R1(V.children[2],"text-emphasis")||(W=f.S?"padding-right":"padding-top",g.R1(V.children[2],
"text-emphasis-position")&&(W=f.S?"padding-left":"padding-bottom"),g.Gs?g.X3(Z,W,"1em"):g.X3(Z,W,"0.5em")))}f.FL=t;f.Yj=Z;f.V.push(k)},cte=function(f){if(f.Z){var k=f.Z;
if(f.j6){var G=f.B.textAlign;G===0?(k=k.firstElementChild)&&g.X3(k,{"border-bottom-left-radius":"0"}):G===1&&(k=k.lastElementChild)&&g.X3(k,{"border-bottom-right-radius":"0"})}}f.Z=g.o1("SPAN");g.X3(f.Z,{display:"block"});g.bD(f.Z,"caption-visual-line");f.W.appendChild(f.Z)},pMs=function(f,k){var G=g.o1("SPAN");
g.X3(G,{display:"inline-block","white-space":"pre-wrap"});g.X3(G,SBM(f,k));G.classList.add("ytp-caption-segment");f.Z.appendChild(G);f.j6&&f.W.children.length>1&&(f=f.B.textAlign,f===0?G.previousElementSibling||g.X3(G,{"border-top-left-radius":"0"}):f===1&&g.X3(G,{"border-top-right-radius":"0"}));G.previousElementSibling&&(g.X3(G.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.X3(G,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return G},
JtY=function(f,k,G){if(f===255&&k===255||!f&&!k)return{BZ:f,
bm:k,result:0};f=YBA[f];k=YBA[k];if(f&128){var t;if(t=!(k&128))t=k,t=G.n1()&&G.bm===t;if(t)return{BZ:f,bm:k,result:1}}else if(k&128&&1<=f&&f<=31)return{BZ:f,bm:k,result:2};return{BZ:f,bm:k,result:3}},kG6=function(f,k,G,t){k===255&&G===255||!k&&!G?(++f.W===45&&f.reset(),f.S.K.clear(),f.Z.K.clear()):(f.W=0,f3n(f.S,k,G,t))},GGs=function(f,k){f.B.sort((G,t)=>{var Z=G.time-t.time;
return Z===0?G.order-t.order:Z});
for(let G of f.B)f.time=G.time,G.type===0?kG6(f,G.DR,G.qm,k):G.type===1&&f.K&496&&f3n(f.Z,G.DR,G.qm,k);f.B.length=0},ogM=function(f,k){switch(f){case 0:return tyM[(k&127)-32];
case 1:return ZWH[k&15];case 2:return u1C[k&31];case 3:return hKC[k&31]}return 0},Bd=function(f,k){if(f.style.type===3){var G=0,t=0,Z=f.Z.time+0,u="",h="",W=Z;
for(var D=1;D<=15;++D){var V=!1;for(var U=t?t:1;U<=32;++U){var e=f.W[D][U];if(e.B!==0){G===0&&(G=D,t=U);V=String.fromCharCode(e.B);var q=e.timestamp;q<Z&&(Z=q);e.timestamp=W;h&&(u+=h,h="");u+=V;V=!0}if((e.B===0||U===32)&&V){h="\n";break}else if(t&&!V)break}if(G&&!V)break}u&&k.S(G,t,Z,W,u)}else for(t=G=0,u=Z=f.Z.time+0,h=1;h<=15;++h)for(W="",D=1;D<=32;++D)if(U=f.W[h][D],e=U.B,e!==0&&(G===0&&(G=h,t=D),V=String.fromCharCode(e),q=U.timestamp,q<=Z&&(Z=q),W+=V,U.reset()),D===32||e===0)W&&k.S(G,t,Z,u,W),
Z=u,W="",t=G=0},jp=function(f){return f.W[f.row][f.K]},NL=function(f,k,G){k>=2&&f.K>1&&(--f.K,jp(f).B=0);
var t=jp(f);t.timestamp=f.Z.time+0;t.B=ogM(k,G);f.K<32&&f.K++},Whe=function(f,k,G,t){for(let h=0;h<t;h++)for(let W=0;W<=32;W++){var Z=f.W[k+h][W],u=f.W[G+h][W];
Z.B=u.B;Z.timestamp=u.timestamp}},Ut=function(f,k,G){for(let t=0;t<G;t++)for(let Z=0;Z<=32;Z++)f.W[k+t][Z].reset()},ep=function(f){f.row=f.B>0?f.B:1;
f.K=1;Ut(f,0,15)},Du6=function(f){f.style.set(1);
f.B=f.S;f.B.B=0;f.B.style=f.style;f.W.mode=1<<f.B.S},yr=function(f,k,G){var t=f.K,Z=!1;
switch(f.style.get()){case 4:case 1:case 2:f.style.get()===4&&t.B>0||(Bd(t,G),ep(f.K),ep(f.S),t.row=15,t.B=k,Z=!0)}f.style.set(3);f.B=t;f.B.style=f.style;f.W.mode=1<<t.S;Z?t.K=1:t.B!==k&&(t.B>k?(Bd(t,G),Ut(t,t.row-t.B,k)):t.row<k&&(k=t.B),t.B=k)},Vya=function(f){f.style.set(4);
f.B=f.text;f.B.style=f.style;f.W.mode=1<<f.B.S},f3n=function(f,k,G,t){f.K.update();
k=JtY(k,G,f.K);switch(k.result){case 0:return;case 1:case 2:return}var Z=k.BZ;k=k.bm;if(32<=Z||!Z)f.B.mode&f.B.K&&(G=Z,G&128&&(G=127),k&128&&(k=127),f=f.S.B,G&96&&NL(f,0,G),k&96&&NL(f,0,k),G!==0&&k!==0&&f.style.type===3&&Bd(f,t));else if(Z&16)a:if(!f.K.matches(Z,k)&&(G=f.K,G.BZ=Z,G.bm=k,G.state=2,G=Z&8?f.A:f.W,f.S=G,f.B.mode=1<<(f.Z<<2)+(G.Z<<1)+(G.style.type===4?1:0),(f.B.mode|1<<(f.Z<<2)+(G.Z<<1)+(G.style.type!==4?1:0))&f.B.K))if(k&64){t=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(Z&7)<<1|k>>5&1];
f=k&16?((k&14)>>1)*4:0;k=G.B;switch(G.style.get()){case 4:t=k.row;break;case 3:if(t!==k.row){if(t<k.B&&(t=k.B,t===k.row))break;var u=1+k.row-k.B;let h=1+t-k.B;Whe(k,h,u,k.B);G=u;Z=k.B;h<u?(u=h+Z-u,u>0&&(G+=u,Z-=u)):(u=u+Z-h,u>0&&(Z-=u));Ut(k,G,Z)}}k.row=t;k.K=f+1}else switch(Z&7){case 1:switch(k&112){case 32:NL(G.B,0,32);break a;case 48:k===57?(t=G.B,jp(t).B=0,t.K<32&&t.K++):NL(G.B,1,k&15)}break;case 2:k&32&&NL(G.B,2,k&31);break;case 3:k&32&&NL(G.B,3,k&31);break;case 4:case 5:if(32<=k&&k<=47)switch(k){case 32:Du6(G);
break;case 33:t=G.B;t.K>1&&(--t.K,jp(t).B=0);break;case 36:t=G.B;f=jp(t);for(k=0;k<=15;k++)for(G=0;G<=32;G++)if(t.W[k][G]===f){for(;G<=32;G++)t.W[k][G].reset();break}break;case 37:yr(G,2,t);break;case 38:yr(G,3,t);break;case 39:yr(G,4,t);break;case 40:NL(G.B,0,32);break;case 41:t=G;t.style.set(2);t.B=t.K;t.B.B=0;t.B.style=t.style;t.W.mode=1<<t.B.S;break;case 42:t=G;f=t.text;f.B=15;f.style.set(4);ep(f);Vya(t);break;case 43:Vya(G);break;case 44:f=G;k=f.K;switch(f.style.get()){case 1:case 2:case 3:Bd(k,
t)}Ut(k,0,15);break;case 45:b:{k=G;f=k.B;switch(k.style.get()){default:case 2:case 1:break b;case 4:if(f.row<15){++f.row;f.K=1;break b}break;case 3:}f.B<2&&(f.B=2,f.row<f.B&&(f.row=f.B));k=f.row-f.B+1;Bd(f,t);Whe(f,k,k+1,f.B-1);Ut(f,f.row,1)}break;case 46:Ut(G.S,0,15);break;case 47:f=G,Bd(f.K,t),f.S.updateTime(f.W.time+0),t=f.S,f.S=f.K,f.K=t,Du6(f)}break;case 7:switch(k){case 33:case 34:case 35:t=G.B,(t.K+=k&3)>32&&(t.K=32)}}},BEK=function(f,k,G,t,Z,u,h){var W=u[0],D=h[W.getAttribute("p")];
if(D.Lq===1){var V=u[1],U=u[2];u=u[3];W.getAttribute("t");V.getAttribute("t");U.getAttribute("t");u.getAttribute("t");W.getAttribute("p");V.getAttribute("p");u.getAttribute("p");h=h[U.getAttribute("p")];W=vgn(W.textContent,V.textContent,U.textContent,u.textContent,h);return new qL(f,k,Z,G,W,t,D)}switch(D.Lq){case 9:case 10:D.textEmphasis=1;break;case 11:D.textEmphasis=2;break;case 12:D.textEmphasis=3;break;case 13:D.textEmphasis=4;break;case 14:D.textEmphasis=5}return new qL(f,k,Z,G,W.textContent||
"",t,D)},vgn=function(f,k,G,t,Z){var u=g.vf(),h=u?g.o1("DIV"):g.o1("RUBY"),W=g.o1("SPAN");
W.textContent=f;h.appendChild(W);f=u?g.o1("DIV"):g.o1("RP");f.textContent=k;h.appendChild(f);k=u?g.o1("DIV"):g.o1("RT");k.textContent=G;h.appendChild(k);G=Z.Lq;if(G===10||G===11||G===12||G===13||G===14)if(g.X3(k,"text-emphasis-style","filled circle"),g.X3(k,"text-emphasis-color","currentcolor"),g.X3(k,"webkit-text-emphasis","filled circle"),Z.Lq===11||Z.Lq===13)g.X3(k,"webkit-text-emphasis-position","under left"),g.X3(k,"text-emphasis-position","under left");G=!0;if(Z.Lq===4||Z.Lq===7||Z.Lq===12||
Z.Lq===14)g.X3(h,"ruby-position","over"),g.X3(h,"-webkit-ruby-position","before");else if(Z.Lq===5||Z.Lq===6||Z.Lq===11||Z.Lq===13)g.X3(h,"ruby-position","under"),g.X3(h,"-webkit-ruby-position","after"),G=!1;Z=u?g.o1("DIV"):g.o1("RP");Z.textContent=t;h.appendChild(Z);u&&(t=G,g.X3(h,{display:"inline-block",position:"relative"}),u=h.firstElementChild.nextElementSibling,g.X3(u,"display","none"),u=u.nextElementSibling,g.X3(u,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.X3(h.lastElementChild,"display","none"),t?(g.X3(h,"padding-top","0.6em"),g.X3(u,"top","0")):(g.X3(h,"padding-bottom","0.6em"),g.X3(u,"bottom","0")));return h},jia=function(f){var k="_"+Ot++;
return new Pd(0,0x8000000000000,0,k,f)},Qr=function(f,k){f=f.getAttribute(k);
if(f!=null)return Number(f)},I2=function(f,k){f=f.getAttribute(k);
if(f!=null)return f==="1"},Fd=function(f,k){f=Qr(f,k);
return f!==void 0?f:null},KR=function(f,k){f=f.getAttribute(k);
if(f!=null)return An.test(f),f},NEC=function(f,k){var G={},t=k.getAttribute("ws");
Object.assign(G,t?f.O[t]:f.S);f=Fd(k,"mh");f!=null&&(G.Ve=f);f=Fd(k,"ju");f!=null&&(G.textAlign=f);f=Fd(k,"pd");f!=null&&(G.RL=f);f=Fd(k,"sd");f!=null&&(G.IT=f);f=KR(k,"wfc");f!=null&&(G.windowColor=f);k=Qr(k,"wfo");k!==void 0&&(G.windowOpacity=k/255);return G},Uu6=function(f,k){var G={},t=k.getAttribute("wp");
t&&Object.assign(G,f.C[t]);f=Fd(k,"ap");f!=null&&(G.vM=f);f=Qr(k,"cc");f!=null&&(G.d_=f);f=Qr(k,"ah");f!=null&&(G.DB=f);f=Qr(k,"rc");f!=null&&(G.ov=f);k=Qr(k,"av");k!=null&&(G.MU=k);return G},eKb=function(f,k,G,t){var Z={};
Object.assign(Z,Uu6(f,k));Object.assign(Z,NEC(f,k));t?g.TK(Z,f.S)?(t=f.Z,Z=f.S):t="_"+Ot++:t=k.getAttribute("id")||"_"+Ot++;f=Qr(k,"t")+G;k=Qr(k,"d")||0x8000000000000;if(Z.RL===2||Z.RL===3)G=Z.ov,Z.ov=Z.d_,Z.d_=G;return new Pd(f,k,0,t,Z)},$s=function(f){f=g.$D(Math.round(f),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-f.length)+f},yLI=function(f,k,G,t,Z){t===0&&(t=0x8000000000000);
var u={};k.wpWinPosId&&Object.assign(u,f.S.get(k.wpWinPosId));k.wsWinStyleId&&Object.assign(u,f.Z.get(k.wsWinStyleId));f=k.rcRowCount;f!==void 0&&(u.ov=f);k=k.ccColCount;k!==void 0&&(u.d_=k);if(u.RL===2||u.RL===3)k=u.ov,u.ov=u.d_,u.d_=k;return new Pd(G,t,0,Z,u)},iJ=function(f){var k=f.byteOffset;
f.byteOffset+=1;return f.B.getUint8(k)},ze=function(f){var k=f.byteOffset;
f.byteOffset+=4;return f.B.getUint32(k)},PDA=function(f){if(typeof f==="string")return!1;
f=new qKn(f,0);return OWi(f)},OWi=function(f){if(!(f.byteOffset<f.B.byteLength)||ze(f)!==1380139777)return!1;
f.version=iJ(f);if(f.version>1)return!1;iJ(f);iJ(f);iJ(f);return!0},QiM=function(f,k){if(!k)return"";
f.S&&f.K.params.IT!==1&&(k*=-1);return`translate${f.S?"X":"Y"}(${k}px)`},I3C=function(f){f.Do=Array.from(f.element.getElementsByClassName("caption-visual-line"));
for(var k=f.K.params.ov,G=0,t=0,Z=f.Do.length-1;G<k&&Z>-1;){var u=f.Do[Z];t+=f.S?u.offsetWidth:u.offsetHeight;G++;Z--}f.Ky=t;k=Math;G=k.max;isNaN(f.VG)&&((t=f.B.d_)?(Z=g.o1("SPAN"),g.N6(Z,"\u2013".repeat(t)),g.X3(Z,SBM(f,f.B.PO)),f.W.appendChild(Z),f.VG=Z.offsetWidth,f.W.removeChild(Z)):f.VG=0);t=f.W;k=G.call(k,f.VG,f.EQ,(f.S?t.offsetHeight:t.offsetWidth)+1);f.Bc&&(k=Math.min(k,f.maxWidth));f.S6=k},FhA=function(f,k){I3C(f);
var G=f.Do.reduce((t,Z)=>(f.S?Z.offsetWidth:Z.offsetHeight)+t,0);
G=f.Ky-G;if(G!==f.XL){let t=G>0&&f.XL===0,Z=G<f.XL;k||isNaN(G)||t||!Z||(g.bD(f.element,"ytp-rollup-mode"),f.U(f.element,"transitionend",f.RI));g.X3(f.W,"transform",QiM(f,G));f.XL=G}I3C(f)},KhM=function(f,k,G,t){var {formatId:Z,
wH:u,startTimeMs:h,durationMs:W}=f.jE(k),D={formatId:Z,startTimeMs:h,durationMs:W,p5:u,Nv:u},V=ALp(f.Jy,D.startTimeMs),U=V>=0?f.Jy[V]:null,e=U?U.startTimeMs+U.durationMs:0,q=D.startTimeMs+D.durationMs;!U||D.startTimeMs-e>f.S?f.Jy.splice(V+1,0,D):(U.durationMs=Math.max(e,q)-U.startTimeMs,U.Nv=Math.max(U.Nv,D.Nv));t(f.Jy);t=g.TA(k);f=f.Z;t=t.buffer.slice(t.byteOffset,t.byteLength+t.byteOffset);k=k.info.S;f.S6?f.C==null?g.jS(f.logger,350058965,"Null loaded track meta data at captions data received"):
G.fF(t,f.C,k*1E3):g.jS(f.logger,350058965,"Null Representation at captions data received")},zKK=function(f,k){f.K=(G,t)=>{if(f.D.X().experiments.rH("html5_sabr_live_support_subfragmented_captions"))(f.B?f.B=f.B.Z(G):(f.B=G,$u6(f.B)),f.B)?G.info.Ic&&(iWH(f.B),KhM(f,f.B,k,t),f.B=null):g.jS(f.logger,350058965,"Empty slice");
else if(G.info.Ic){var Z=G;if(f.SF.length>0){for(Z=f.SF.shift();f.SF.length>0;)Z=Z?.Z(f.SF.shift());Z=Z?.Z(G)}Z?($u6(Z),iWH(Z),KhM(f,Z,k,t)):g.jS(f.logger,350058965,"Empty slice")}else f.SF.push(G)};
f.D.addEventListener("sabrCaptionsDataLoaded",f.K)},ALp=function(f,k){f=g.On(f,{startTimeMs:k},(G,t)=>G.startTimeMs-t.startTimeMs);
return f>=0?f:-f-2},$u6=function(f){try{var k=g.cB(f)*1E3}catch(G){k=f.info.segmentStartTime*1E3}k<0&&(k=f.info.segmentStartTime*1E3);
f.info.segmentStartTime=k/1E3;f.info.S=k/1E3},iWH=function(f){try{var k=g.nnO(f)*1E3}catch(G){k=f.info.W*1E3}k<0&&(k=f.info.W*1E3);
f.info.W=k/1E3;f.info.V=k/1E3},CDC=function(f,k){if(!g.DqD(f)||f.B!=null&&g.ct(k,f.B)&&f.B.B.rawcc!=null)return!1;
k=!!f.B&&f.B.isManifestless&&Object.values(f.B.B).some(G=>g.pj(G,"386"));
f=!!f.B&&!f.B.isManifestless&&g.ohD(f.B);return k||f},EgK=function(f,k,G){var t=[];
for(let Z in f.K.B){if(!f.K.B.hasOwnProperty(Z))continue;let u=f.K.B[Z];if(g.pj(u,G||null)){let h=u.info.captionTrack;h&&h.languageCode===k&&t.push(u)}}return t.length?t[0]:null},mup=function(f,k){var G=[];
for(let Z in f.K.B){if(!f.K.B.hasOwnProperty(Z))continue;var t=f.K.B[Z];if(g.pj(t,k||null)){let u=t.info.id,h=u,W=`.${u}`,D="",V="";if(t=t.info.captionTrack)u=t.languageCode,h=t.displayName,W=t.vssId,D=t.kind,V=t.id;G.push(new g.kx({id:Z,languageCode:u,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:W,kind:D,captionId:V}))}}return G},Lhi=function(f){var k=ng6.length;
if(f.byteLength<k)return!1;f=new Uint8Array(f,0,k);for(let G=0;G<k;G++)if(ng6[G]!==f[G])return!1;return!0},CR=function(f){f=f.split(":");
var k=0;for(let G of f)k=k*60+Number(G);return k*1E3},dus=function(f,k,G,t){t=Object.assign({Ve:0},t);
return new Pd(f,k,G,"_"+Ot++,t)},siC=function(f,k,G,t,Z,u,h,W,D){switch(h.tagName){case "b":W.bold=!0;
break;case "i":W.italic=!0;break;case "u":W.underline=!0}for(let U=0;U<h.childNodes.length;U++){var V=h.childNodes[U];if(V.nodeType===3)V=new qL(k,G,t,Z.id,V.nodeValue,u||U>0,g.xM(W)?void 0:W),D.push(V),Z.B.push(V);else{let e={};Object.assign(e,W);siC(f,k,G,t,Z,!0,V,e,D)}}},wki=function(f,k,G){if(typeof k==="string"||PDA(k))return[{trackData:k,
OH:G}];if(typeof k==="string"&&k.substring(0,6)==="WEBVTT"||typeof k!=="string"&&Lhi(k))return[{trackData:k,OH:G}];var t=new DataView(k);if(t.byteLength<=8||t.getUint32(4)!==1718909296)return[];var Z=g.MXu(t);if(f.rM&&Z){var u=g.rl(Z),h=g.Mt(Z);Z=Z.segmentNumber;u&&Z&&f.rM.nV(Z,u,h)}f=g.Yx(t,1835295092);if(!f||!f.length||!f[0].size)return[];u=[];for(h=0;h<f.length;h++)Z=f[h],Z=new Uint8Array(k,Z.dataOffset,Z.size-(Z.dataOffset-Z.offset)),Z=g.i4(Z),u.push({trackData:Z,OH:G+h*1E3});bWe(t,u,G);return u=
u.filter(W=>!!W.trackData)},rLn=function(f,k,G){f.B||(f.B=new a3n);
f=f.B.W(k,G);Math.random()<.01&&g.xi(Error("Deprecated subtitles format in web player: WebVTT"));return f},bWe=function(f,k,G){var t=g.T8(f,0,1836476516),Z=9E4;
t&&(Z=g.RO(t)||9E4);t=0;var u=g.Yx(f,1836019558);for(let W=0;W<u.length;W++){var h=u[W];W<k.length&&(h=g.T8(f,h.dataOffset,1953653094))&&(h=g.T8(f,h.dataOffset,1952867444))&&(h=g.gl(h)/Z*1E3,W===0&&(t=h),k[W].OH=h-t+G||G*W*1E3)}},Mys=function(f){var k={};
if(f=g.uL(f))k.lang=f,g.r9u.test(f)&&(k.RL=1);return k},Et=function(f){return f.W==="HLS"&&f.GS?!0:f.FL&&f.GS&&f.W!=="LIVE"&&f.W!=="SABR_LIVE"},HWi=function(f){return!f.S&&f.FL&&f.NE&&(f.W==="LIVE"||f.W==="SABR_LIVE")},m6=function(f,k,G=!1){var t=f.Bz.Y("enable_player_captions_new_style_defaults")?xuA:XkK,Z=t.PO;
f.Z={};Object.assign(f.Z,t);f.Z.PO={};Object.assign(f.Z.PO,Z);f.A={PO:{}};var u=k.backgroundOverride?f.A:f.Z,h=k.background||Z.background;An.test(h);u.PO.background=h;u=k.colorOverride?f.A:f.Z;h=k.color||Z.color;An.test(h);u.PO.color=h;u=k.windowColorOverride?f.A:f.Z;h=k.windowColor||t.windowColor;An.test(h);u.windowColor=h;u=k.backgroundOpacityOverride?f.A:f.Z;h=k.backgroundOpacity;h==null&&(h=Z.backgroundOpacity);u.PO.backgroundOpacity=h;u=k.fontSizeIncrementOverride?f.A:f.Z;h=k.fontSizeIncrement;
h==null&&(h=Z.fontSizeIncrement);u.PO.fontSizeIncrement=h;h=k.fontStyleOverride?f.A:f.Z;u=k.fontStyle;u==null&&(u=Z.bold&&Z.italic?3:Z.bold?1:Z.italic?2:0);h=h.PO;switch(u){case 1:h.bold=!0;delete h.italic;break;case 2:delete h.bold;h.italic=!0;break;case 3:h.bold=!0;h.italic=!0;break;default:delete h.bold,delete h.italic}u=k.textOpacityOverride?f.A:f.Z;h=k.textOpacity;h==null&&(h=Z.textOpacity);u.PO.textOpacity=h;u=k.windowOpacityOverride?f.A:f.Z;h=k.windowOpacity;h==null&&(h=t.windowOpacity);u.windowOpacity=
h;t=k.charEdgeStyleOverride?f.A:f.Z;u=k.charEdgeStyle;u==null&&(u=Z.charEdgeStyle);t.PO.charEdgeStyle=u;t=k.fontFamilyOverride?f.A:f.Z;u=k.fontFamily;u==null&&(u=Z.fontFamily);t.PO.fontFamily=u;f.loaded&&f.sQ();G&&g.fa("yt-player-caption-display-settings",k,2592E3)},nR=function(f,k,G){k&&!f.Ky?(k=jia({RL:0,
lang:"en"}),f.Ky=[k,new qL(k.start,k.end-k.start,0,k.id,G??"Captions look like this")],f.player.wO(f.Ky)):!k&&f.Ky&&(l3M(f,f.Ky),f.Ky=null)},SKp=function(f){if(f.Bz.Y("enable_player_captions_persistence_state_machine")){var k=g.k9("yt-player-caption-persistence");
if(k==null){let G=g.HY().Pz(65);if(G===!0)k=!1;else{let t=g.Fp(f.Bz)?LR(f):TEM(f);t!=null?k=!!t:G===!1&&(k=!0)}k!==void 0&&dF(f,k)}return k}},LR=function(f){if(!f.D.isInline())return g.k9("yt-player-sticky-caption")},TEM=function(f){if(!f.storage)return null;
try{var k=f.storage.get("module-enabled")}catch(G){f.storage.remove("module-enabled")}return k},bJ=function(f){if(f.Bz.Y("enable_player_captions_persistence_state_machine"))return SKp(f);
var k=void 0,G=g.HY().Pz(65);if(g.Fp(f.Bz)&&G!=null){if(LR(f)!=null)return!1;k=!G}return k},RKn=function(f){if(f.Bz.e9===1||f.videoData.m1===1||g.gR(f.videoData,"yt:cc")==="alwayson")return!0;
if(f.videoData.captionTracks.length)var k=f.getAudioTrack().K;if(f.Bz.Y("enable_player_captions_persistence_state_machine")){var G=SKp(f);if(G!==void 0)return!!G}else if(f.Bz.e9===2&&(g.Fp(f.Bz)?G=LR(f):G=TEM(f),G!=null))return!!G;G=Wd(f.player.getAudioTrack(),g.Fp(f.Bz));var t=g.gR(f.videoData,"yt:cc");if(bJ(f)===void 0){if(G==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return t?t==="on":!0;if(G==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return t==="on"}else return t==="on";return k==="ON"||g.gR(f.videoData,
"yt:cc")==="on"},wF=function(f,k=!1){if(f.K&&!k||!f.videoData.captionTracks.length)return!1;
f=f.getAudioTrack();return!!f.B||f.K==="FORCED_ON"},cLA=function(f,k){if(f.K){var G=f.D.uj().Ay().textTracks,t=null;
f.W==="HLS"?t=f.K.getId():t=f.K.toString();for(let u=0;u<G.length;u++){var Z=G[u];Z.id===t&&(k?Z.mode!=="showing"&&(Z.mode="showing",Z=f.K,f.TL(Z,!!Z,a2(f)?"g":f.V?"m":"s")):Z.mode==="showing"&&(Z.mode="disabled"))}}},a2=function(f){var k=rF(f);
return!!k&&f.K===k},pk6=function(f,k){if(f.W==="HLS")return!1;
g.W4(f.videoData)&&(k=!0);k||(k=f.W==="TTS"?!1:f.W==="INNERTUBE"?!1:!0);return k||f.Bz.Y("web_watch_disable_account_level_captions_settings")&&g.Fp(f.Bz)?!0:!!g.HY().Pz(66)},rF=function(f){return f.O&&f.O.B},ML=function(f,k){if(!f.B)return null;
if(f.O&&f.O.S)return f.O.S;k=pk6(f,k);k=g.$O(f.B.B,k);var G=null;if(m2A(f.Bz)){var t=f.D.isInline()?void 0:g.k9("yt-player-caption-sticky-language");var Z=[t,f.videoData.captionsLanguagePreference,f.Bz.captionsLanguagePreference,g.gR(f.videoData,"yt:cc_default_lang")];let W=!1;for(let D=0;D<Z.length;D++){let V=Z[D];if(V){W=!0;for(var u=0;u<k.length;u++)if(g.uL(k[u])===V)return k[u];for(u=0;u<k.length;u++)if(g.uL(k[u]).split("-")[0]===V.split("-")[0])return k[u]}}if(W&&f.B&&(Z=f.B.O,Z.length))for(var h of Z)if(h.languageCode===
t){G=h;break}}else for(h=[f.videoData.captionsLanguagePreference,f.Bz.captionsLanguagePreference,g.gR(f.videoData,"yt:cc_default_lang")],t=0;t<h.length;t++)for(Z=0;Z<k.length;Z++)if(g.uL(k[Z])===h[t])return k[Z];h=null;f.O&&f.O.W&&(h=f.O.W);h||(h=k.find(W=>W.isDefault)||null);
h||(h=k[0]||rF(f));h&&G&&g.uL(h).split("-")[0]!==G.languageCode.split("-")[0]&&(h=ESY(h,G));return h},ggI=function(f,k){var G=g.$O(f.B.B,!0),t=[];
for(let Z=0;Z<G.length;Z++){let u=G[Z],h=g.o1("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.t5(u));h.setAttribute("srclang",g.uL(u));h.setAttribute("id",u.toString());f.S6||h.setAttribute("src",f.B.V(u,"vtt"));u===k&&h.setAttribute("default","1");t.push(h)}k=f.D.uj();k.Ky(t);t=k.Ay();f.NE&&(f.Bz.bb().B.Pz(g.Rr)&&f.ME&&(f.Zo.jd(f.ME),f.ME=null),f.ME=f.Zo.U(t.textTracks,"change",f.EQ))},lJ=function(f,k,G){f.loaded&&f.unload();
G!=null&&(f.V=G,f.V&&(f.Bz.Y("enable_player_captions_persistence_state_machine")?dF(f,!!k):g.Fp(f.Bz)?Hd(f,!!k):xs(f,!!k)));k!==null||wF(f,!0)||f.TL(k,!!k,f.V?"m":"s");f.K=k;wF(f)&&(f.K=rF(f));Xd(f,f.K??void 0);f.load()},dF=function(f,k){f.Bz.Y("enable_player_captions_persistence_state_machine")&&g.fa("yt-player-caption-persistence",k,3122064E3)},Hd=function(f,k){f.D.isInline()||g.fa("yt-player-sticky-caption",k,2592E3)},xs=function(f,k){if(f.storage)try{f.storage.set("module-enabled",k)}catch(G){}},
Xd=function(f,k){f.Bz.Y("html5_modify_caption_vss_logging")&&(f.videoData.Rv=k)},JLn=function(f,k){var G=f.Do[k.id];
G&&G.K!==k&&(G.dispose(),delete f.Do[k.id],G=null);G||(G=YKY(f,k))&&(f.Do[k.id]=G)},f_s=function(f,k){var G=k.windowId;
f.Cy[G]||(f.Cy[G]=[]);f.Cy[G].push(k)},YKY=function(f,k){var G=kpA(f);
if(!G)return null;var t=f.K?g.uL(f.K):null;t&&g.r9u.test(t)&&(k.params.RL=1);var Z=f.RI.getPlayerSize();t=Z.height*f.kj.height;Z=Z.width*f.kj.width;f.Bz.playerStyle!=="google-live"||f.Z.isDefault||Object.assign(k.params,f.Z);switch(k.params.Ve!=null?k.params.Ve:k.B.length>1?1:0){case 1:return new GpK(k,f.Z,f.A,G.width,G.height,Z,t,f.Bz.experiments,f.cz.bind(f),f.D);case 2:return new tzi(k,f.Z,f.A,G.width,G.height,Z,t,f.Bz.experiments,f.cz.bind(f),f.D);default:return new Te(k,f.Z,f.A,G.width,G.height,
Z,t,f.Bz.experiments,f.cz.bind(f),f.D)}},kpA=function(f){var k=f.RI.getVideoContentRect(!0).height,G=f.RI.getVideoContentRect(!0).width;
if(!k||!G)return null;k*=f.kj.height;G*=f.kj.width;return{width:G,height:k}},l3M=function(f,k){f.player.pl(k);
for(let G of k)g.We(f.VG,G);o2(f.Yj)},Zen=function(f,k){if(!f.B)return{};
if(k){g.xM(k)||f.iJ(k.vss_id,"m");if(f.S&&f.W!=="HLS"||!g.AQ(k))return;if(g.xM(k)){lJ(f,null,!0);return}let t;var G=g.$O(f.B.B,!0);for(let Z=0;Z<G.length;Z++){let u=G[Z];u.languageCode!==k.languageCode||t&&(u.languageName!==k.languageName||(u.captionId||"")!==(k.captionId||"")||g.t5(u)!==k.displayName)||(t=k.translationLanguage?ESY(u,k.translationLanguage):u)}f.Rk(k.position);!t||t===f.K&&f.loaded||(k=g.cC(),G=g.uL(t),k.length&&G===k[k.length-1]||(k.push(G),g.fa("yt-player-caption-language-preferences",
k)),m2A(f.Bz)&&!f.D.isInline()&&g.fa("yt-player-caption-sticky-language",G,2592E3),lJ(f,t,!0))}else return f.loaded&&f.K&&!a2(f)?g.Zo(f.K):{};return""};
g.Sn.prototype.nV=g.ua(67,function(f,k,G){this.K.set(f,{MR:k,xt:G})});
g.Rj.prototype.nV=g.ua(66,function(f,k,G){this.S6.nV(f,k,G)});
g.n3.prototype.Ky=g.ua(65,function(){return!1});
g.n3.prototype.Z=g.ua(64,function(){});
g.L3.prototype.Z=g.ua(63,function(f,k,G){this.xj();this.W();CoW(this,f,k,G)});
g.d7.prototype.Z=g.ua(62,function(f,k,G){this.xj();k=this.V(f,k);this.W();this.K=g.aE(k,{format:"RAW",onSuccess:t=>{this.K=null;var Z=t.getResponseHeader&&t.getResponseHeader("Content-Length")?Number(t.getResponseHeader("Content-Length")):0;G.fF(t.responseText,f,void 0,void 0,Z)},
withCredentials:!0})});
g.Dv.prototype.C=g.ua(61,function(){this.mediaElement.C()});
g.uz.prototype.C=g.ua(60,function(){var f=g.Tx(document,"track",void 0,this.B);for(let k=0;k<f.length;k++)g.BS(f[k])});
g.Dv.prototype.Yj=g.ua(59,function(){return this.mediaElement.Yj()});
g.uz.prototype.Yj=g.ua(58,function(){return!(!this.B.textTracks||!this.B.textTracks.addEventListener)});
g.Dv.prototype.ME=g.ua(57,function(){return this.mediaElement.ME()});
g.uz.prototype.ME=g.ua(56,function(){return!!this.B.textTracks});
g.Dv.prototype.Ky=g.ua(55,function(f){this.mediaElement.Ky(f)});
g.uz.prototype.Ky=g.ua(54,function(f){for(let k=0;k<f.length;k++)this.B.appendChild(f[k])});
g.oj.prototype.iJ=g.ua(40,function(f,k){this.app.ub().iJ(f,k)});
g.mf.prototype.iJ=g.ua(39,function(f,k){this.N.iJ(f,k)});
g.Aj.prototype.iJ=g.ua(38,function(f,k){f=[f,k];g.x$(this,g.T0(this.provider),"cfi",f)});
g.$z.prototype.iJ=g.ua(37,function(f,k){this.qoe&&this.qoe.iJ(f,k)});
g.wd.prototype.iJ=g.ua(36,function(f,k){this.p7.iJ(f,k)});
g.xz.prototype.iJ=g.ua(35,function(){});
g.EC.prototype.iJ=g.ua(34,function(f,k){g.oH(this,37,[f,k])});
g.oj.prototype.TL=g.ua(33,function(f,k,G){this.app.ub().TL(f,k,G)});
g.mf.prototype.TL=g.ua(32,function(f,k,G){this.N.TL(f,k,G)});
g.Aj.prototype.TL=g.ua(31,function(f,k,G){if(this.Yj!==f||this.sQ!==k)k=k==="rawcc"?"":k,G=[f,k,this.Yj,G],g.x$(this,g.T0(this.provider),"cfs",G),this.Yj=f,this.sQ=k});
g.$z.prototype.TL=g.ua(30,function(f,k,G){this.qoe&&this.qoe.TL(f,k,G)});
g.wd.prototype.TL=g.ua(29,function(f,k,G){this.p7.TL(f,k,G)});
g.xz.prototype.TL=g.ua(28,function(){});
g.EC.prototype.TL=g.ua(27,function(f,k,G){g.oH(this,36,[f,k,G])});
g.R6.prototype.pB=g.ua(9,function(f){return(f=this.W(f))?f.B:0});
g.ya.prototype.pB=g.ua(8,function(){return 0});
var sup=/#(.)(.)(.)/,d26=/^#(?:[0-9a-f]{3}){1,2}$/i,uep={en:"English"},hpH=class extends g.n3{constructor(f){super(f);this.K=new Set}A(f){var k=this.yG.uj();if(k&&k.Ay()){k=k.Ay().textTracks;for(let G of k)G.kind==="subtitles"&&!this.K.has(G.language)&&G.language&&(g.RY(this.B,new g.kx({languageCode:G.language,languageName:G.language,kind:G.kind,id:G.id,displayName:uep[G.label]||G.label,vss_id:`.${G.language}`})),this.K.add(G.language))}g.$O(this.B).length>0&&f.aL()}},ovi=class{constructor(){this.segments=
[]}contains(f){f=g.On(this.segments,f);return f>=0||f<0&&(-f-1)%2===1}length(){return this.segments.length/2}},W9e=class extends g.I0{constructor(f,k,G,t,Z,u){super();this.policy=f;this.player=k;this.qE=G;this.C=t;this.Z=Z;this.Ky=u;this.S=new ovi;this.A=-1;this.K=this.W=this.B=null;this.S6=0;this.V=new g.CW(this.Zo,1E3,this);this.events=new g.Vq(this);g.w(this,this.V);g.w(this,this.events);this.events.U(k,"SEEK_COMPLETE",this.O);this.O();this.Zo()}GB(){super.GB();this.K&&this.K.cancel()}O(){this.seekTo(this.player.getCurrentTime())}seekTo(f){f-=
this.player.jj();var k=this.B;this.B=g.Md(this.qE.V(f).f7);k!==this.B&&this.Ky&&this.Ky()}reset(){this.S=new ovi;this.A=-1;this.K&&(this.K.cancel(),this.K=null)}Zo(){this.xj();var f;if(f=this.B!=null)f=this.B,f=f.qE.S(f);if(f&&!this.K&&!(this.B&&this.B.segmentStartTime-this.player.getCurrentTime()>30)){f=this.B;f=f.qE.Yj(f);let Z=f.f7[0];if(this.player.getVideoData().enableServerStitchedDai){var k=this.player.D$();if(k){var G=Z.qE.info.id;let u=Z.wH;var t=f.f7[0].S;if(this.policy.ME){if(k=g.wW6(k,
t,u,G,3))f.S=k}else if(G=k.d2(t,u,G,3))if(t=2,k.CH.has(u)?t=0:g.C_(k,u)&&(t=1),k=t,k===0)G&&(f.B=new g.A3(G));else if(k===2){this.V.start();a1a(this)&&this.seekTo(this.player.getCurrentTime());return}}}Z.qE.index.B3(Z.wH)?(this.S.contains(f.f7[0].wH)||rta(this,f),this.B=g.Md(f.f7)):a1a(this)&&this.seekTo(this.player.getCurrentTime())}this.V.start()}},D5a=class extends g.n3{constructor(f,k){super(k);this.K=f;this.D=k;this.C=null;this.Zo=!1;this.logger=new g.Bz("caps");this.S6=g.ct(this.D,this.K)}Z(f,
k,G){this.W();k=MHe(this,f.getId());k||(k=f.languageCode,k=this.K.isManifestless?HXM(this,k,"386"):HXM(this,k));if(k){var t=(k.index.pB(k.index.lN())-k.index.getStartTime(k.index.lN()))*1E3,Z=new g.AJQ(this.D.X());this.C=new W9e(Z,this.D,k,(u,h)=>{G.fF(u,f,h,t)},this.S6||g.Kk(k.info),()=>{this.C&&this.C.reset();
this.Zo=!0})}}Ky(){var f=this.Zo;
this.Zo=!1;return f}A(f){var k=this.D.X().Y("html5_fallback_if_rawcc_missing");var G=this.K.B.rawcc!=null;if(!this.S6||!G&&k)k=this.K.isManifestless?x2n(this,"386"):x2n(this);else{if(!G){g.jS(this.logger,386248249,"rawcc used but unavailable");return}k=[new g.kx({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.kx({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let t of k)g.RY(this.B,
t);f.aL()}W(){this.C&&(this.C.dispose(),this.C=null)}V(){return""}},An=/^#(?:[0-9a-f]{3}){1,2}$/i;var VzH=["left","right","center","justify"];var qL=class extends g.hg{constructor(f,k,G,t,Z,u=!1,h=null){super(f,f+k,{priority:G,namespace:"captions"});this.windowId=t;this.text=Z;this.append=u;this.B=h}toString(){return super.toString()}};var Te=class extends g.J{constructor(f,k,G,t,Z,u,h,W,D,V){var U=V.isInline()&&!0,e={};Object.assign(e,k);Object.assign(e,f.params);Object.assign(e,G);var q={};Object.assign(q,k.PO);f.params.PO&&Object.assign(q,f.params.PO);Object.assign(q,G.PO);U&&(q.background&&(e.windowColor=q.background),e.windowOpacity=.6,q.backgroundOpacity=0);e.PO=q;var O=e.RL===1,F=[{G:"span",j:"captions-text",J:{style:"word-wrap: normal; display: block;"}}],m=W.rH("caption_edit_on_hover")&&V.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
m&&F.unshift({G:"button",j:"caption-edit",J:{tabindex:"0","aria-label":bXi()},L:[{G:"svg",J:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},L:[{G:"path",J:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({G:"div",j:"caption-window",J:{id:`caption-window-${f.id}`,dir:O?"rtl":"ltr",tabindex:"0",lang:e.lang},L:F});this.experiments=
W;this.V=[];this.ME=!1;this.K=f;this.FL=this.Yj=null;this.ho=u;this.X5=h;this.Z=null;this.maxWidth=u*.96;this.maxHeight=h*.96;this.B=e;this.Jh=G;this.kj=k;this.W=this.At("captions-text");f=this.W.style;this.j6=W.rH("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in f||"WebkitBoxDecorationBreak"in f);this.cz=XMW(t,Z,u,h);this.bj=D;m&&(this.A=this.At("caption-edit"),this.U(this.A,"click",()=>{this.bj()}));
this.type=0;this.Ee=this.cz*l1M(q);this.Oe=U;this.NE=W.rH("enable_centered_caption_for_tvfilm_video")&&V.getVideoData().isTvfilmVideo;this.O=V.X().bb().B.Pz(g.jSH);this.Bc=V.X().bb().B.Pz(g.N3D);t=new g.E6(this.element,!0);g.w(this,t);t.subscribe("dragstart",this.Al,this);t.subscribe("dragmove",this.Rp,this);t.subscribe("dragend",this.pE,this);this.GS=this.sQ=this.Y9=this.Me=0;t="";this.B.windowOpacity&&(t=Di(this.B.windowColor),t="rgba("+t[0]+","+t[1]+","+t[2]+","+this.B.windowOpacity+")");Z={"background-color":t,
display:this.B.isVisible===!1?"none":"","text-align":VzH[this.B.textAlign]};this.j6&&(Z["border-radius"]=t?`${this.Ee*.25}px`:"");(this.S=this.K.params.RL===2||this.K.params.RL===3)&&ThW(this,this.element);g.X3(this.element,Z);U&&this.element.parentElement?.style.setProperty("--caption-window-color",t);switch(this.B.vM){case 0:case 1:case 2:g.bD(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.bD(this.element,"ytp-caption-window-bottom")}}Al(f,k){this.sQ=f;this.GS=k;var G=g.Zg(this.element,
this.element.parentElement);this.Me=f-G.x;this.Y9=k-G.y}Rp(f,k){if(f!==this.sQ||k!==this.GS){g.sK(this.element,"ytp-dragging")||g.bD(this.element,"ytp-dragging");var G=g.hC(this.element);f=f-this.Me-.02*this.ho;var t=k-this.Y9-.02*this.X5,Z=(f+G.width/2)/this.maxWidth*3;Z=Math.floor(g.$D(Z,0,2));var u=(t+G.height/2)/this.maxHeight*3;u=Math.floor(g.$D(u,0,2));k=Z+u*3;f=(f+Z/2*G.width)/this.maxWidth;f=g.$D(f,0,1)*100;G=(t+u/2*G.height)/this.maxHeight;G=g.$D(G,0,1)*100;this.K.params.vM=k;this.K.params.MU=
G;this.K.params.DB=f;this.K.params.isDefault=!1;this.B.vM=k;this.B.MU=G;this.B.DB=f;this.B.isDefault=!1;this.kj.vM=k;this.kj.MU=G;this.kj.DB=f;this.kj.isDefault=!1;this.ux()}}pE(){g.ai(this.element,"ytp-dragging")}ux(){this.C(this.V)}C(f){var k=this.Oe?0:Math.min(this.Pc(),this.maxWidth),G=this.bx(),t=this.Oe;if(t){var Z=getComputedStyle(this.W.parentNode);Z=vd(Z.borderLeftWidth)+vd(Z.borderRightWidth)+vd(Z.paddingLeft)+vd(Z.paddingRight)}else Z=0;var u="";this.K.params.RL===3&&(u="rotate(180deg)");
var h=t?`calc(96% - ${Z}px)`:"96%";g.X3(this.element,{top:0,left:0,right:"",bottom:"",width:k?`${k}px`:"",height:G?`${G}px`:"","max-width":h,"max-height":h,margin:"",transform:""});this.Cy(f);u={transform:u,top:"",left:"",width:k?`${k}px`:"",height:G?`${G}px`:"","max-width":"","max-height":""};h=this.B.vM;var W=this.B.DB,D=this.B.MU;this.NE&&h!=null&&(W=50,h=Math.floor(h/3)*3+1);W=W*.96+2;switch(h){case 0:case 3:case 6:(t=this.B.PO.fontSizeIncrement)&&t>0&&this.B.RL!==2&&this.B.RL!==3&&(W=Math.max(W/
(1+t*2),2));u.left=`${W}%`;break;case 1:case 4:case 7:u.left=`${W}%`;let V=0;this.O||(V=this.W.offsetWidth);k||V?(k=k||V+1,u.width=`${k}px`,u["margin-left"]=t?`${k/-2-Z/2}px`:`${k/-2}px`):(this.O&&(u.width="max-content"),u.transform+=" translateX(-50%)");break;case 2:case 5:case 8:u.right=`${100-W}%`}t=D*.96+2;switch(h){case 0:case 1:case 2:u.top=`${t}%`;break;case 3:case 4:case 5:u.top=`${t}%`;t=0;this.O||(t=this.element.clientHeight);(G=G||t)?(u.height=`${G}px`,u["margin-top"]=`${G/-2}px`):u.transform+=
" translateY(-50%)";break;case 6:case 7:case 8:u.bottom=`${100-t}%`}if(this.Bc){switch(h){case 0:case 3:case 6:G=Math.max(0,100-2*W);break;case 2:case 5:case 8:G=Math.max(0,100-2*(100-W));break;default:G=Math.max(0,2*Math.min(W-2,98-W))}u["max-width"]=Z>0?`calc(${G}% - ${Z}px)`:`${G}%`}g.X3(this.element,u);this.A&&(this.O?G=this.Ee:(f=Rss(this,f),G=this.NE?f>0?this.W.offsetHeight/f:0:this.W.offsetHeight/f),this.A.style.height=`${G}px`,this.A.style.width=`${G}px`,this.element.style.paddingLeft=`${G+
5}px`,this.element.style.paddingRight=`${G+5}px`,this.O||(f=Number(this.element.style.marginLeft.replace("px",""))-G-5,G=Number(this.element.style.marginRight.replace("px",""))-G-5,this.element.style.marginLeft=`${f}px`,this.element.style.marginRight=`${G}px`))}Cy(f){if(this.type===0&&this.K.params.ov!==void 0&&this.experiments.rH("web_enable_popon_asr_captions")){var k=f,G=this.K.params.ov;if(k.length===0||G<=0)f=[];else{f=[];for(let Z=k.length-1;Z>=0;Z--){var t=k[Z];f.unshift(t);let u=Rss(this,
f);if(u>G){f.shift();typeof t.text==="string"&&(k=t.text.split("\n"),G=u-G,k.length-G>0&&(t=new qL(t.start,t.end-t.start,t.priority||0,t.windowId,k.slice(G).join("\n"),t.append,t.B),f.unshift(t)));break}}}}for(t=0;t<f.length&&f[t]===this.V[t];t++);if(this.ME||this.V.length>t)t=0,this.ME=!1,this.V=[],this.Z=this.FL=this.Yj=null,g.Vj(this.W);for(;t<f.length;t++)gSn(this,f[t])}Pc(){return 0}bx(){return 0}toString(){return super.toString()}};var BBi=class{constructor(){this.W=this.time=this.mode=this.K=0;this.S=new vvW(this);this.Z=new vvW(this);this.B=[];this.clear()}clear(){this.W=this.time=this.mode=0;this.B=[];this.reset()}reset(){this.mode=0;this.S.reset(0);this.Z.reset(1)}},YBA=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],j8M=class{constructor(){this.type=0}set(f){this.type=f}get(){return this.type}},NB6=class{constructor(){this.state=this.bm=this.BZ=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}n1(){return this.state!==0}matches(f,k){return this.n1()&&f===this.BZ&&k===this.bm}},U5e=class{constructor(){this.timestamp=this.B=0}reset(){this.timestamp=
this.B=0}},Sp=class{constructor(f){this.Z=f;this.W=[];this.B=this.K=this.row=0;this.style=new j8M;this.S=0;for(f=0;f<=15;f++){this.W[f]=[];for(let k=0;k<=32;k++)this.W[f][k]=new U5e}}updateTime(f){for(let k=1;k<=15;++k)for(let G=1;G<=32;++G)this.W[k][G].timestamp=f}debugString(){var f="\n";for(let k=1;k<=15;++k){for(let G=1;G<=32;++G){let t=this.W[k][G];f=t.B===0?f+"_":f+String.fromCharCode(t.B)}f+="\n"}return f}reset(f){for(let k=0;k<=15;k++)for(let G=0;G<=32;G++)this.W[k][G].reset();this.S=f;this.B=
0;this.K=this.row=1}},tyM=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],ZWH=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],u1C=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],hKC=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],epe=class{constructor(f){this.W=f;this.Z=0;this.style=new j8M;this.A=new Sp(this.W);this.V=new Sp(this.W);this.text=new Sp(this.W);this.K=this.A;this.S=this.V;this.B=this.K}reset(f,k){this.Z=k;this.style.set(2);this.K=this.A;this.S=this.V;this.B=this.K;var G=(f<<2)+(k<<1);this.A.reset(G);this.V.reset(G);this.text.reset((f<<
2)+(k<<1)+1)}},vvW=class{constructor(f){this.B=f;this.Z=0;this.W=new epe(this.B);this.A=new epe(this.B);this.K=new NB6;this.S=this.W}reset(f){this.Z=f;this.K.clear();this.S=this.W;this.W.reset(f,0);this.A.reset(f,1)}};var y2K=class{S(){}};var R2=class extends g.I0{reset(){}};var Pd=class extends g.hg{constructor(f,k,G,t,Z){super(f,f+k,{priority:G,namespace:"captions"});this.id=t;this.params=Z;this.B=[]}toString(){return super.toString()}},Ot=0;var qvp=class extends R2{constructor(f){super();this.S=f;this.pens={};this.C={};this.O={};this.Z="_"+Ot++;this.V={};this.K=this.B=null;this.A=!0}reset(){this.V={};this.K=this.B=null;this.A=!0}W(f,k){f=f.firstChild;f.getAttribute("format");k=k||0;Number.isFinite(k);f=Array.from(f.childNodes);for(var G of f)if(G.nodeType===1)switch(G.tagName){case "head":var t=G;break;case "body":var Z=G}if(t){t=Array.from(t.childNodes);for(var u of t)if(u.nodeType===1)switch(u.tagName){case "pen":G=u.getAttribute("id");
t=this.pens;f={};var h=u.getAttribute("p");h&&Object.assign(f,this.pens[h]);h=I2(u,"b");h!=null&&(f.bold=h);h=I2(u,"i");h!=null&&(f.italic=h);h=I2(u,"u");h!=null&&(f.underline=h);h=Fd(u,"et");h!=null&&(f.charEdgeStyle=h);h=Fd(u,"of");h!=null&&(f.offset=h);h=KR(u,"bc");h!=null&&(f.background=h);h=KR(u,"ec");h!=null&&(f.Q7=h);h=KR(u,"fc");h!=null&&(f.color=h);h=Fd(u,"fs");h!=null&&h!==0&&(f.fontFamily=h);h=Qr(u,"sz");h!==void 0&&(f.fontSizeIncrement=h/100-1);h=Qr(u,"bo");h!==void 0&&(f.backgroundOpacity=
h/255);h=Qr(u,"fo");h!==void 0&&(f.textOpacity=h/255);h=Fd(u,"rb");h!=null&&h!==10&&h!==0&&(f.Lq=h>10?h-1:h);h=Fd(u,"hg");h!=null&&(f.Qd=h);t[G]=f;break;case "ws":t=u.getAttribute("id");this.O[t]=NEC(this,u);break;case "wp":t=u.getAttribute("id"),this.C[t]=Uu6(this,u)}}if(Z){u=[];Z=Array.from(Z.childNodes);for(m of Z)if(m.nodeType===1)switch(m.tagName){case "w":this.B=eKb(this,m,k,!1);(Z=this.V[this.B.id])&&Z.end>this.B.start&&(Z.end=this.B.start);this.V[this.B.id]=this.B;u.push(this.B);break;case "p":var W=
m;f=k;Z=[];t=W.getAttribute("w")||this.Z;G=!!I2(W,"a");f=(Qr(W,"t")||0)+f;h=Qr(W,"d")||5E3;G||(!this.A&&this.K&&this.K.windowId===t&&this.K.end>f&&(this.K.end=f),this.K&&this.K.text==="\n"&&(this.K.text=""));let a=G?6:5;var D=W.getAttribute("p");D=D?this.pens[D]:null;let r=Array.from(W.childNodes);r.length&&(this.A=W.getAttribute("d")!=null);for(W=0;W<r.length;W++){var V=r[W];var U=void 0;W>0&&(G=!0);let X;V.nodeType===1&&(X=V);if(X&&X.tagName==="s"){if((V=(V=X.getAttribute("p"))?this.pens[V]:null)&&
V.Lq&&(V.Lq===1?(V=r.slice(W,W+4),V.length===4&&(U=BEK(f,h,t,G,a,V,this.pens),W+=3)):U=BEK(f,h,t,G,a,[X],this.pens)),!U){var e=X;U=f;V=h;var q=t,O=G;let l=e.textContent?e.textContent:"";var F=e.getAttribute("p");F=F?this.pens[F]:null;e=Qr(e,"t")||0;U=new qL(U+e,V-e,a,q,l,O,F)}}else U=new qL(f,h,a,t,V.textContent||"",G,D);Z.push(U);this.K=U}if(Z.length>0){Z[0].windowId===this.Z&&(this.B=eKb(this,m,k,!0),u.push(this.B));for(let X of Z)X.windowId=this.B.id,this.B.B.push(X),u.push(X)}}var m=u}else m=
[];return m}};var OeA=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),PTs=class extends R2{constructor(f){super();this.A=f;this.B=new Map;this.S=new Map;this.Z=new Map;this.K=new Map}reset(){this.K.clear()}W(f,k){f=JSON.parse(f);if(!f)return[];if(f.pens){var G=f.pens,t=0;for(var Z of G){G={};var u=Z.pParentId;u&&Object.assign(G,this.B.get(u));Z.bAttr&&(G.bold=!0);Z.iAttr&&(G.italic=!0);Z.uAttr&&(G.underline=!0);u=Z.ofOffset;u!=null&&(G.offset=u);Z.szPenSize!==void 0&&(G.fontSizeIncrement=Z.szPenSize/100-1);
u=Z.etEdgeType;u!=null&&(G.charEdgeStyle=u);Z.ecEdgeColor!==void 0&&(G.Q7=$s(Z.ecEdgeColor));u=Z.fsFontStyle;u!=null&&u!==0&&(G.fontFamily=u);Z.fcForeColor!==void 0&&(G.color=$s(Z.fcForeColor));Z.foForeAlpha!==void 0&&(G.textOpacity=Z.foForeAlpha/255);Z.bcBackColor!==void 0&&(G.background=$s(Z.bcBackColor));Z.boBackAlpha!==void 0&&(G.backgroundOpacity=Z.boBackAlpha/255);(u=Z.rbRuby)&&u!==10&&(G.Lq=u>10?u-1:u,G.textEmphasis=OeA.get(G.Lq));Z.hgHorizGroup&&(G.Qd=Z.hgHorizGroup);this.B.set(t++,G)}}if(f.wsWinStyles){t=
f.wsWinStyles;Z=0;for(var h of t)t={},(G=h.wsParentId)?Object.assign(t,this.Z.get(G)):Object.assign(t,this.A),h.mhModeHint!==void 0&&(t.Ve=h.mhModeHint),h.juJustifCode!==void 0&&(t.textAlign=h.juJustifCode),h.pdPrintDir!==void 0&&(t.RL=h.pdPrintDir),h.sdScrollDir!==void 0&&(t.IT=h.sdScrollDir),h.wfcWinFillColor!==void 0&&(t.windowColor=$s(h.wfcWinFillColor)),h.wfoWinFillAlpha!==void 0&&(t.windowOpacity=h.wfoWinFillAlpha/255),this.Z.set(Z++,t)}if(f.wpWinPositions){Z=f.wpWinPositions;h=0;for(var W of Z)Z=
{},(t=W.wpParentId)&&Object.assign(Z,this.S.get(t)),W.ahHorPos!==void 0&&(Z.DB=W.ahHorPos),W.apPoint!==void 0&&(Z.vM=W.apPoint),W.avVerPos!==void 0&&(Z.MU=W.avVerPos),W.ccCols!==void 0&&(Z.d_=W.ccCols),W.rcRows!==void 0&&(Z.ov=W.rcRows),this.S.set(h++,Z)}if(f.events){f=f.events;W=[];for(let R of f)if(h=(R.tStartMs||0)+k,Z=R.dDurationMs||0,R.id)t=String(R.id),f=yLI(this,R,h,Z,t),W.push(f),this.K.set(t,f);else{R.wWinId?t=R.wWinId.toString():(t="_"+Ot++,f=yLI(this,R,h,Z,t),W.push(f),this.K.set(t,f));
var D;f=W;var V=R;Z===0&&(Z=5E3);G=this.K.get(t);let ZO=(u=!!V.aAppend)?6:5,Of=V.segs,ia=null;V.pPenId&&(ia=this.B.get(V.pPenId));for(V=0;V<Of.length;V++){var U=Of[V],e=U.utf8;if(e){var q=U.tOffsetMs||0;let zD=null;U.pPenId&&(zD=this.B.get(U.pPenId));if((G.params.Ve!=null?G.params.Ve:G.B.length>1?1:0)===2&&u&&e==="\n")continue;U=null;var O=[];if(D=zD&&zD.Lq===1)a:{D=Of;var F=V;if(F+3>=D.length||!D[F+1].pPenId||!D[F+2].pPenId||!D[F+3].pPenId){D=!1;break a}var m=D[F+1].pPenId;(m=this.B.get(m))&&m.Lq&&
m.Lq===2?(m=D[F+2].pPenId,m=this.B.get(m),!m||!m.Lq||m.Lq<3?D=!1:(m=D[F+3].pPenId,D=(m=this.B.get(m))&&m.Lq&&m.Lq===2?!0:!1)):D=!1}if(D)q=Of[V+1].utf8,U=Of[V+3].utf8,D=Of[V+2].utf8,F=this.B.get(Of[V+2].pPenId),e=vgn(e,q,D,U,F),U=new qL(h,Z,ZO,t,e,u,zD),V+=3;else{if(e.indexOf("<")>-1){O=zD;D=ia;F=h;m=Z;var a=q,r=ZO,X=u;let la=[];var l=g.wP(`<html>${e}</html>`);if(!l.getElementsByTagName("parsererror").length&&l.firstChild?.childNodes.length)for(let JQ of l.firstChild.childNodes){l=JQ.textContent?.replace(/\n/g,
"")??"";if(JQ.nodeType===3&&(!l||l.match(/^ *$/)!=null))continue;let oN={};Object.assign(oN,O||D);switch(JQ?.tagName){case "b":oN.bold=!0;break;case "i":oN.italic=!0;break;case "u":oN.underline=!0}la.push(new qL(F+a,m-a,r,G.id,l,X,oN))}O=la}O.length||(O=[new qL(h+q,Z-q,ZO,G.id,e,u,zD||ia)])}if(O.length)for(let la of O)f.push(la),G.B.push(la);else U&&(f.push(U),G.B.push(U))}u=!0}}k=W}else k=[];return k}};var Q8s=class extends g.n3{constructor(f,k,G){super(f);this.videoData=k;this.audioTrack=G;this.O=k.Hp}Z(f,k,G){LrI(this.videoData.videoId,f.vssId,G.fF)}A(f){if(this.audioTrack)for(let k of this.audioTrack.captionTracks)g.RY(this.B,k);f.aL()}};var GpK=class extends Te{constructor(f,k,G,t,Z,u,h,W,D,V){super(f,k,G,t,Z,u,h,W,D,V);this.type=1}Cy(f){var k=this.K.B;super.Cy(f);for(f=f.length;f<k.length;f++){let Z=k[f],u;if(t&&Z.B===G)u=t;else{u={};Object.assign(u,Z.B);Object.assign(u,I_n);var G=Z.B;var t=u}gSn(this,Z,u)}}},I_n={QF:!0};var qKn=class extends y2K{constructor(f,k){super();this.trackData=f;this.A=k;this.version=this.Z=this.W=this.byteOffset=0;this.K=[];this.B=new DataView(this.trackData)}S(f,k,G,t,Z){if(G<t){let u="_"+Ot++;G=G/1E3-this.A;t=t/1E3-this.A;f=new Pd(G,t-G,5,u,{textAlign:0,vM:0,DB:k*2.5,MU:f*5.33});Z=new qL(G,t-G,5,u,Z);this.K.push(f);this.K.push(Z)}}},F9a=class extends R2{constructor(f,k){super();this.K=f;this.S=k;this.track=this.S.languageName==="CC3"?4:0;this.B=new BBi;this.B.K=1<<this.track}W(f){f=new qKn(f,
this.K);if(OWi(f)){for(;f.byteOffset<f.B.byteLength;)for(f.version===0?f.W=ze(f)*(1E3/45):f.version===1&&(f.W=ze(f)*4294967296+ze(f)),f.Z=iJ(f);f.Z>0;f.Z--){var k=iJ(f);let G=iJ(f),t=iJ(f);k&4&&(k&3)===this.track&&(this.track===0||this.track===1)&&(k=this.B,k.B.push({time:f.W,type:this.track,DR:G,qm:t,order:k.B.length}))}GGs(this.B,f);return f.K}return[]}reset(){this.B.clear()}};var tzi=class extends Te{constructor(f,k,G,t,Z,u,h,W,D,V){super(f,k,G,t,Z,u,h,W,D,V);this.type=2;this.Do=[];this.S6=this.Ky=this.XL=0;this.VG=NaN;this.EQ=0;this.Yf=null;this.Bv=new g.CW(this.RI,433,this);this.A&&(V.createClientVe(this.A,this,167342),this.U(this.A,"click",()=>{V.logClick(this.A)}),f=new g.E6(this.element,!0),g.w(this,f),f.subscribe("hoverstart",()=>{V.logVisibility(this.A,!0)},this));
g.bD(this.element,"ytp-caption-window-rollup");g.w(this,this.Bv);g.X3(this.element,"overflow","hidden")}ux(){g.mh(this.Bv)}RI(){this.element.removeEventListener("transitionend",this.RI,!1);g.ai(this.element,"ytp-rollup-mode");this.C(this.Yf,!0)}bx(){return this.S?this.S6:this.Ky}Pc(){return this.S?this.Ky:this.S6}C(f,k){this.Yf=f;if(this.K.params.ov){var G=0;for(let t=0;t<this.V.length&&G<f.length;t++)this.V[t]===f[G]&&G++;G>0&&G<f.length&&(f=this.V.concat(f.slice(G)));this.EQ=this.S6;this.Ky=this.S6=
0;super.C(f);FhA(this,k)}super.C(f)}};var A2C=class{constructor(f,k,G,t){this.D=f;this.Z=k;this.logger=G;this.qe=t;this.Jy=[];this.B=null;this.W=[];this.SF=[];this.K=null;this.OQ={RNB:()=>this.K,
tY:()=>this.Jy,
kUt:Z=>{this.W=Z},
noH:()=>this.W};
f=this.D.X().experiments.B("html5_override_micro_discontinuities_threshold_ms");this.S=f>0?f:10}unload(){this.K!=null&&(this.D.removeEventListener("sabrCaptionsDataLoaded",this.K),this.K=null);this.Jy=[];this.B=null;this.W=[];this.D.publish("sabrCaptionsBufferedRangesUpdated",this.Jy)}jE(f){return{formatId:g.zZ(f.info.qE.info,this.qe),wH:f.info.wH+(this.qe?0:1),startTimeMs:f.info.S*1E3,durationMs:f.info.V*1E3}}};var K9C=class extends g.n3{constructor(f,k){super(k);this.K=f;this.D=k;this.logger=new g.Bz("caps");this.C=this.S6=null;this.Zo=new A2C(this.D,this,this.logger,this.K.qe)}Z(f,k,G){this.W();k=f.getId();k=k!=null&&k in this.K.B?this.K.B[k]:null;k||(k=f.languageCode,k=this.K.isManifestless?EgK(this,k,"386"):EgK(this,k));k&&(this.C=f,this.S6=k,zKK(this.Zo,G),this.D.publish("sabrCaptionsTrackChanged",g.zZ(k.info,this.K.qe)))}A(f){var k=this.K.isManifestless?mup(this,"386"):mup(this);for(let G of k)g.RY(this.B,
G);f.aL()}W(){this.C&&(this.C=this.S6=null,this.Zo.unload(),this.D.publish("sabrCaptionsTrackChanged",null))}V(){return""}};var ng6="WEBVTT".split("").map(f=>f.charCodeAt(0)),a3n=class extends R2{constructor(){super()}W(f,k){f instanceof ArrayBuffer&&(f=g.i4(new Uint8Array(f)));
var G=[];f=f.split($5C);for(let F=1;F<f.length;F++){var t=f[F],Z=k;if(t!==""&&!ieA.test(t)){var u=cd.exec(t);if(u&&u.length>=4){var h=CR(u[1]),W=CR(u[2])-h;h+=Z;var D=(u=u[3])?u.split(" "):[];u={};var V=null;var U="";var e=null,q="";for(let m of D){D=m.split(":");if(D.length!==2)continue;var O=D[1];switch(D[0]){case "line":D=O.split(",");D[0].endsWith("%")&&(V=D[0],u.MU=Number.parseInt(V,10),D.length===2&&(U=D[1].trim()));break;case "position":D=O.split(",");e=D[0];u.DB=Number.parseInt(e,10);D.length===
2&&(q=D[1].trim());break;case "align":switch(O){case "start":u.textAlign=0;break;case "middle":u.textAlign=2;break;case "end":u.textAlign=1}}}V||U||(U="end");if(!e)switch(u.textAlign){case 0:u.DB=0;break;case 1:u.DB=100;break;case 2:u.DB=50}if(u.textAlign!=null){V=0;switch(U){case "center":V+=3;break;case "end":V+=6;break;default:V+=0}switch(q){case "line-left":V+=0;break;case "center":V+=1;break;case "line-right":V+=2;break;default:switch(u.textAlign){case 0:V+=0;break;case 2:V+=1;break;case 1:V+=
2}}U=V<0||V>8?7:V;u.vM=U}t=t.substring(cd.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");q=u;u={};if(t.indexOf("<")<0&&t.indexOf("&")<0)Z=dus(h,W,5,q),h=new qL(h,W,5,Z.id,t,!1,g.xM(u)?void 0:u),G.push(Z),G.push(h),Z.B.push(h);else for(U=t.split(zpW),U.length===1?(t=5,q=dus(h,W,t,q)):(V=t=6,q=Object.assign({d_:32},q),q=new Pd(h,W,V,"_"+Ot++,q)),G.push(q),V=h,e=0;e<U.length;e++)if(D=U[e],e%2===0){O=g.wP(`<html>${D}</html>`);let m;O.getElementsByTagName("parsererror").length?(m=O.createElement("span"),
m.appendChild(O.createTextNode(D))):m=O.firstChild;siC(this,V,W-(V-h),t,q,e>0,m,u,G)}else V=CR(D)+Z}cd.lastIndex=0}}return G}},ieA=/^NOTE/,$5C=/(?:\r\n|\r|\n){2,}/,cd=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),zpW=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var CTn=class extends g.I0{constructor(f,k){super();this.D=f;this.Bz=k;this.B=null;this.rM=this.D.D$();this.logger=new g.Bz("caps")}clear(){this.B&&this.B.dispose();this.B=null}reset(){this.B&&this.B.reset()}GB(){super.GB();this.clear()}};var XkK={windowColor:"#080808",windowOpacity:0,textAlign:2,vM:7,DB:50,MU:100,isDefault:!0,PO:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},xuA={windowColor:"#080808",windowOpacity:0,textAlign:0,vM:7,DB:50,MU:100,isDefault:!0,PO:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.S6("captions",class extends g.my{constructor(f){super(f);this.D=f;this.VG=[];this.Do={};this.Cy={};this.V=!1;this.W="NONE";this.B=this.O=this.Ky=this.j6=this.Oe=null;this.Bc={aL:()=>{this.aL()},
fF:(t,Z,u,h,W=0)=>{var D=Number(this.videoData.X().bb().B.Pz(g.iSQ)??0);W>0&&D>0&&this.videoData.lengthSeconds>0&&W/this.videoData.lengthSeconds>D?this.D.Wz("tts",{dropcap:W}):this.fF(t,Z,u,h)}};
this.ME=this.K=null;this.Bz=this.D.X();this.videoData=this.D.getVideoData();this.RI=this.D.K7();this.Z={PO:{}};this.A={PO:{}};g.UA(this.videoData)?this.W="OFFLINE":g.KfX(this.videoData,this.D)?this.W="HLS":CDC(this.videoData,this.D)?this.W="SABR_LIVE":g.$JQ(this.videoData,this.D)?this.W="LIVE":this.videoData.captionTracks.length?this.W="INNERTUBE":this.videoData.Cy&&(this.W="TTS");this.FL=this.Bz.controlsType==="3";this.Ee=new CTn(this.D,this.Bz);this.Zo=new g.Vq(this);this.C=new g.J({G:"div",j:"ytp-caption-window-container",
J:{id:"ytp-caption-window-container"}});this.kj={top:0,right:0,bottom:0,left:0,width:1,height:1};var k=null,G=g.Uv("yt-html5-player-modules::subtitlesModuleData");G&&(k=new g.h2(G));this.storage=k;k=f.uj();this.GS=!!k?.ME();this.NE=!!k?.Yj();this.S=Et(this);this.S6=HWi(this);g.w(this,this.Ee);this.S?this.XL=this.Yj=null:(this.Yj=new g.zG(this.Y9,void 0,this),g.w(this,this.Yj),this.XL=new g.CW(this.Bv,2E3,this),g.w(this,this.XL));g.w(this,this.Zo);g.c4(this.player,this.C.element,4);g.w(this,this.C);
this.S||this.Zo.U(f,"resize",this.sQ);k=g.VK(this.Bz)&&!g.xK()&&!this.D.isFullscreen();G=this.Bz.bb().B.Pz(g.Rr)&&g.lP(this.Bz)&&g.kc;(this.Me=(k||G)&&!this.S&&!this.S6)&&this.Zo.U(f,k?"resize":"fullscreentoggled",this.Pc);this.Zo.U(f,"onPlaybackAudioChange",this.bx);this.Zo.U(f,g.tp("captions"),t=>{this.onCueRangeEnter(t)});
this.Zo.U(f,g.Z5("captions"),t=>{this.onCueRangeExit(t)});
m6(this,Vr()||{});g.mM(this.player,"onCaptionsModuleAvailable");this.W==="HLS"&&this.S&&(f=this.D.uj().Ay(),this.NE&&this.Zo.U(f.textTracks,"addtrack",this.L7))}GB(){if(this.S||this.S6){let f=this.D.uj();f&&!f.xj()&&f.C()}else nR(this,!1);super.GB()}f8(){return this.Bz.Y("html5_honor_caption_availabilities_in_audio_track")&&this.W!=="LIVE"&&this.W!=="SABR_LIVE"}ZY(){if(this.FL)return this.S||this.S6;if(this.W==="HLS")return this.S;var f=this.getAudioTrack();if(this.f8()){if(!f.captionTracks.length)return!1;
if(!this.B)return!0}f=Wd(f,g.Fp(this.Bz));return f==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:f==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?wF(this):bJ(this)||wF(this)?!0:RKn(this)}load(){super.load();this.O=this.getAudioTrack();if(this.B)this.K&&(this.Ee.clear(),this.S?cLA(this,!0):this.player.getPresentingPlayerType()!==3&&this.B.Z(this.K,"json3",this.Bc),this.W!=="HLS"&&this.S||this.S6||a2(this)||g.mM(this.player,"captionschanged",g.Zo(this.K)));else{let f;this.W==="OFFLINE"?f=new Q8s(this.player,this.videoData,
this.getAudioTrack()):this.W==="SABR_LIVE"?f=new K9C(this.videoData.B,this.player):this.W==="HLS"?f=new hpH(this.player):this.W==="LIVE"?f=new D5a(this.videoData.B,this.player):this.W==="INNERTUBE"?f=new g.L3(this.player,this.videoData,this.getAudioTrack()):f=new g.d7(this.player,this.videoData.Cy,this.videoData.videoId,g.yB6(this.videoData),this.videoData.m8,this.videoData.eventId);this.B=f;g.w(this,this.B);this.B.A(this.Bc)}}unload(){this.S&&this.K?cLA(this,!1):(this.XL&&this.XL.IS(),this.player.yP("captions"),
this.VG=[],this.B&&this.B.W(),this.Ee.clear(),this.Ky&&this.player.wO(this.Ky),this.sQ());super.unload();this.player.Ez();g.mM(this.player,"captionschanged",{})}create(){this.ZY()&&this.load();var f;a:{if(this.Bz.Y("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(f=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let k of f)if(k.kind==="asr"&&k.languageCode===
"en"){f=!0;break a}f=!1}f&&this.D.publish("showpromotooltip",this.C.element)}aL(){var f=Wd(this.player.getAudioTrack(),g.Fp(this.Bz));f=f==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?ML(this,this.V):f==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&wF(this)?rF(this):bJ(this)||this.V||RKn(this)?ML(this,this.V):wF(this)?rF(this):null;this.W!=="HLS"&&this.S||this.S6?ggI(this,f):(!this.K&&f&&lJ(this,f),g.mM(this.player,"onCaptionsTrackListChanged"),g.nz(this.player,"onApiChange"))}EQ(){var f=this.D.uj().Ay().textTracks,
k=null;for(let G=0;G<f.length;G++)if(f[G].mode==="showing")a:{k=g.$O(this.B.B,!0);for(let t=0;t<k.length;t++)if(k[t].toString()===f[G].id){k=k[t];break a}k=null}(this.loaded?this.K:null)!==k&&lJ(this,k,!0)}L7(){this.B?.A(this.Bc)}bq(){!this.K&&this.S||this.unload()}fF(f,k,G,t){if(f){Xd(this,this.K??void 0);this.B.Ky()&&(this.VG=[],this.D.yP("captions"),o2(this.Yj),this.Ee.reset());a:{var Z=this.Ee;t=t||0;G=wki(Z,f,G||0);f=[];try{for(let r of G){let X=r.trackData,l=r.OH,R=Z.Bz.Y("safari_live_drm_captions_fix");
if(typeof X!=="string"){G=f;var u=G.concat;if(R&&Lhi(X))var h=rLn(Z,X,l);else{var W=Z,D=k,V=X,U=l,e=t;if(!PDA(V))throw Error("Invalid binary caption track data");W.B||(W.B=new F9a(e,D));h=W.B.W(V,U)}var q=u.call(G,h)}else{if(X.substring(0,6)==="WEBVTT")var O=f.concat(rLn(Z,X,l));else{G=f;var F=G.concat;b:{D=Z;W=k;if(X[0]==="{")try{D.B||(D.B=new PTs(Mys(W)));var m=D.B.W(X,l);break b}catch(ia){g.PZ(ia);m=[];break b}let ZO=g.wP(X);if(!ZO||!ZO.firstChild){let ia=Error("Invalid caption track data");ia.params=
X;throw ia;}if(ZO.firstChild.tagName==="timedtext"){if(Number(ZO.firstChild.getAttribute("format"))===3){V=ZO;D.B||(D.B=new qvp(Mys(W)));m=D.B.W(V,l);break b}let ia=Error("Unsupported subtitles format in web player (Format2)");ia.params=X;throw ia;}if(ZO.firstChild.tagName==="transcript"){let ia=Error("Unsupported subtitles format in web player (Format1)");ia.params=X;throw ia;}let Of=Error("Invalid caption track data");Of.params=X;throw Of;}O=F.call(G,m)}q=O}f=q}var a=f;break a}catch(r){g.jS(Z.logger,
187101178,`Captions parsing failed: ${r.message}. `);Z.clear();a=[];break a}a=void 0}this.Bz.Y("html5_sabr_live_support_subfragmented_captions")&&this.B instanceof K9C&&(k=this.B.Zo,Z=[],a.length>0&&(Z=a.slice(k.W.length)),k.W=!k.B||k.B.info.Ic?[]:a,a=Z);a.length>0&&(k=this.K,this.TL(k,!!k,a2(this)?"g":this.V?"m":"s"));this.player.wO(a,void 0,this.W==="LIVE"||this.W==="SABR_LIVE");!this.V||this.S6||a2(this)||g.H8(this.Bz)||g.Db(this.Bz)||g.rN(this.Bz)||this.Bz.Do==="shortspage"||this.player.isInline()||
(this.XL.IS(),a=jia({vM:0,DB:5,MU:5,ov:2,textAlign:0,RL:0,lang:"en"}),this.j6=[a],k=["Click "," for settings"],this.Oe||(Z=new g.Ky(g.qU()),g.w(this,Z),this.Oe=Z.element),Z=a.end-a.start,(q=g.t5(this.K))&&this.j6.push(new qL(a.start,Z,0,a.id,q)),this.j6.push(new qL(a.start,Z,0,a.id,k[0]),new qL(a.start,Z,0,a.id,this.Oe,!0),new qL(a.start,Z,0,a.id,k[1],!0)),this.player.wO(this.j6),g.EK(this.XL));!this.V||this.S6||a2(this)||(this.Bz.Y("enable_player_captions_persistence_state_machine")?dF(this,!0):
g.Fp(this.Bz)?Hd(this,!0):xs(this,!0),this.O&&(this.O.S=this.K),this.player.Ez());this.V=!1}}onCueRangeEnter(f){this.VG.push(f);o2(this.Yj)}onCueRangeExit(f){g.We(this.VG,f);this.B instanceof D5a&&this.B.S6&&this.player.pl([f]);o2(this.Yj)}getCaptionWindowContainerId(){return this.C.element.id}Bv(){l3M(this,this.j6);this.j6=null}Y9(){if(!this.Me||!this.S){this.Yj.stop();g.X6(this.Cy);this.VG.sort(g.GY);var f=this.VG;if(this.Ky){let k=g.TD(f,function(G){return this.Ky.indexOf(G)===-1},this);
k.length&&(f=k)}for(let k of f)k instanceof Pd?JLn(this,k):f_s(this,k);for(let [k,G]of Object.entries(this.Do)){let t=k,Z=G;this.Cy[t]?(Z.element.parentNode||(Z instanceof tzi||Z instanceof GpK||g.En(this.Do,(u,h)=>{h!==t&&u.K.params.vM===Z.K.params.vM&&u.K.params.DB===Z.K.params.DB&&u.K.params.MU===Z.K.params.MU&&(u.dispose(),delete this.Do[h]);return h===t},this),this.C.element.appendChild(Z.element)),Z.C(this.Cy[t])):(Z.dispose(),delete this.Do[t])}}}XM(){m6(this,{},!0);
g.mM(this.player,"captionssettingschanged")}wQ(){var f=this.Bz.Y("enable_player_captions_new_style_defaults")?xuA:XkK,k=f.PO;f={background:k.background,backgroundOpacity:k.backgroundOpacity,charEdgeStyle:k.charEdgeStyle,color:k.color,fontFamily:k.fontFamily,fontSizeIncrement:k.fontSizeIncrement,fontStyle:k.bold&&k.italic?3:k.bold?1:k.italic?2:0,textOpacity:k.textOpacity,windowColor:f.windowColor,windowOpacity:f.windowOpacity};k=Vr()||{};k.background!=null&&(f.background=k.background);k.backgroundOverride!=
null&&(f.backgroundOverride=k.backgroundOverride);k.backgroundOpacity!=null&&(f.backgroundOpacity=k.backgroundOpacity);k.backgroundOpacityOverride!=null&&(f.backgroundOpacityOverride=k.backgroundOpacityOverride);k.charEdgeStyle!=null&&(f.charEdgeStyle=k.charEdgeStyle);k.charEdgeStyleOverride!=null&&(f.charEdgeStyleOverride=k.charEdgeStyleOverride);k.color!=null&&(f.color=k.color);k.colorOverride!=null&&(f.colorOverride=k.colorOverride);k.fontFamily!=null&&(f.fontFamily=k.fontFamily);k.fontFamilyOverride!=
null&&(f.fontFamilyOverride=k.fontFamilyOverride);k.fontSizeIncrement!=null&&(f.fontSizeIncrement=k.fontSizeIncrement);k.fontSizeIncrementOverride!=null&&(f.fontSizeIncrementOverride=k.fontSizeIncrementOverride);k.fontStyle!=null&&(f.fontStyle=k.fontStyle);k.fontStyleOverride!=null&&(f.fontStyleOverride=k.fontStyleOverride);k.textOpacity!=null&&(f.textOpacity=k.textOpacity);k.textOpacityOverride!=null&&(f.textOpacityOverride=k.textOpacityOverride);k.windowColor!=null&&(f.windowColor=k.windowColor);
k.windowColorOverride!=null&&(f.windowColorOverride=k.windowColorOverride);k.windowOpacity!=null&&(f.windowOpacity=k.windowOpacity);k.windowOpacityOverride!=null&&(f.windowOpacityOverride=k.windowOpacityOverride);return f}Hf(f,k){var G={};Object.assign(G,Vr());Object.assign(G,f);m6(this,G,k);g.mM(this.player,"captionssettingschanged")}sQ(){!this.S&&this.loaded&&(g.is(this.Do,function(f,k){f.dispose();delete this.Do[k]},this),this.Y9())}Z6(f,k){switch(f){case "fontSize":if(isNaN(k))break;
f=g.$D(k,-2,4);this.Hf({fontSizeIncrement:f});return f;case "reload":k&&!this.S&&lJ(this,this.K,!0);break;case "stickyLoading":k!==void 0&&this.Bz.Zo&&(this.Bz.Y("enable_player_captions_persistence_state_machine")?dF(this,!(!k||!k.userInitiated)):g.Fp(this.Bz)?Hd(this,!!k):xs(this,!!k));break;case "track":return Zen(this,k);case "tracklist":return this.B?g.SF(g.$O(this.B.B,!(!k||!k.includeAsr)),G=>g.Zo(G)):[];
case "translationLanguages":return this.B?this.B.O.map(G=>Object.assign({},G)):[];
case "sampleSubtitles":this.S||k===void 0||nR(this,!!k);break;case "sampleSubtitlesCustomized":this.S||nR(this,!!k,k);break;case "recommendedTranslationLanguages":return g.cC();case "defaultTranslationSourceTrackIndices":return this.B?this.B.kj:[]}}getOptions(){var f="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Bz.Zo&&f.push("stickyLoading");return f}TK(){var f=this.K;if(this.D.iN("captions")){if(this.Bz.Y("html5_modify_caption_vss_logging"))return(f=this.videoData.Rv??
null)?{cc:g.JiH(f)}:{};if(f){let k=f.vssId;f.translationLanguage&&k&&(k=`t${k}.${g.uL(f)}`);return{cc:k}}}return{}}H7(f){this.isSubtitlesOn()?(this.Bz.Y("enable_player_captions_persistence_state_machine")&&f?dF(this,!1):g.Fp(this.Bz)?Hd(this,!1):xs(this,!1),Xd(this),lJ(this,null,!0)):this.Bf(f)}Bf(f){var k=a2(this)||!this.K?ML(this,!0):this.K;k&&this.iJ(k.vssId,"m");this.isSubtitlesOn()||lJ(this,k,this.Bz.Y("enable_player_captions_persistence_state_machine")?f:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.K&&!a2(this)}bx(){var f=a2(this);wF(this,f)?lJ(this,this.getAudioTrack().B,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.f8()&&(this.V=!1,this.K=null,this.B&&(this.B.dispose(),this.B=null)),this.ZY()&&(f?lJ(this,ML(this,!1),!1):this.load()))}Rk(f){f&&(this.kj={top:f.top,right:f.right,bottom:f.bottom,left:f.left,width:1-f.left-f.right,height:1-f.top-f.bottom},this.C.element.style.top=`${this.kj.top*100}%`,this.C.element.style.left=`${this.kj.left*100}%`,this.C.element.style.width=
`${this.kj.width*100}%`,this.C.element.style.height=`${this.kj.height*100}%`,this.C.element.style.position="absolute",f=kpA(this))&&(this.C.element.style.width=`${f.width}px`,this.C.element.style.height=`${f.height}px`)}onVideoDataChange(f,k){f==="newdata"&&(this.videoData=k,this.loaded&&this.unload(),this.V=!1,this.K=null,this.B&&(this.B.dispose(),this.B=null,g.mM(this.player,"captionschanged",{})),this.ZY()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}Pc(){if(this.Bz.bb().B.Pz(g.Rr)){this.loaded&&
this.unload();this.ME&&(this.Zo.jd(this.ME),this.ME=null);var f=this.D.uj();f&&!f.xj()&&f.C();this.FL=this.D.isFullscreen()||this.Bz.controlsType==="3";this.S=Et(this);this.S6=HWi(this);this.B&&(this.S||this.S6)&&ggI(this,null)}else(f=this.D.uj())&&!f.xj()&&f.C(),this.D.isFullscreen()?(this.S=this.FL=!0,this.loaded&&this.aL()):(this.FL=this.Bz.controlsType==="3",this.S=Et(this));lJ(this,this.K)}cz(){var f=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
f&&g.$P(this.player,"innertubeCommand",f)}TL(f,k,G){var t=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,Z="";f&&(Z=f.vssId,Z=Z.replace(t,""));var u="";f&&f.getId()&&(u=f.getId()||"");f&&f.getXtags()&&(f=f.getXtags(),f=f.replace(t,""),u=u.concat(`;${f}`));this.W==="HLS"&&(u="");this.D.TL(k?Z:"",k?u:"",G)}iJ(f,k){f=(f||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");f.length>0&&this.D.iJ(f,k)}});})(_yt_player);
