(function(g){var window=this;'use strict';var J2n=function(f,k){g.$P(f,"onAutonavCoundownStarted",k)},fRM=function(f){return f.isBackground()&&f.Yo()},kSY=function(f,k){k=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
f.Ky=k?.navigationEndpoint;k=k?.trackingParams;f.playButton&&k&&f.D.setTrackingParams(f.playButton.element,k)},hU=function(f){var k=ZS(f),G=Math,t=G.min;
var Z=f.V?Date.now()-f.V:0;G=t.call(G,Z,k);u0(f,Math.ceil((k-G)/1E3));k-G<=500&&f.B()?f.select(!0):f.B()&&f.C.start()},og=function(f){var k=f.D.l1(!0,f.D.isFullscreen());
g.Mu(f.container.element,"ytp-autonav-endscreen-small-mode",f.JR(k));g.Mu(f.container.element,"ytp-autonav-endscreen-is-premium",!!f.suggestion&&!!f.suggestion.O$);g.Mu(f.D.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!f.D.q_());g.Mu(f.D.getRootNode(),"countdown-running",f.B());g.Mu(f.container.element,"ytp-player-content",f.D.q_());f.D.Y("web_post_play_autonav_embiggening")||g.X3(f.overlay.element,{width:`${k.width}px`});if(f.D.Y("web_post_play_autonav_embiggening")){var G=f.D.getRootNode().getBoundingClientRect();
k=Math.min(720,G.width*.5);var t=k*.5625;G=G.height-36-60;t>G&&(t=G,k=16/9*t);g.X3(f.K.At("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${t}px`,width:`${k}px`});g.X3(f.container.element,{width:`${k}px`})}f.B()||(f.D.q_()?u0(f,Math.round(ZS(f)/1E3)):u0(f),k=!!f.suggestion&&!!f.suggestion.J0,t=f.D.getVideoData(),t=t.autonavState===1&&t.Bv&&f.D.q_()?!1:f.D.q_()||!(f.suggestion&&f.suggestion.J0),g.Mu(f.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!t&&k),g.Mu(f.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",t&&!k),f.A.Ne(f.D.q_()))},u0=function(f,k=-1){f=f.K.At("ytp-autonav-endscreen-upnext-header");
g.Vj(f);if(k>=0){k=String(k);let G="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],t="Up next in $SECONDS".indexOf(G);if(t>=0){f.appendChild(g.WS("Up next in $SECONDS".slice(0,t)));let Z=g.o1("span");g.dE(Z,"ytp-autonav-endscreen-upnext-header-countdown-number");g.N6(Z,k);f.appendChild(Z);f.appendChild(g.WS("Up next in $SECONDS".slice(t+G.length)));return}}g.N6(f,"Up next")},ZS=function(f){return f.D.isFullscreen()?(f=f.D.getVideoData().l6,f===-1||f===void 0?8E3:f):f.D.Gx()>=0?f.D.Gx():
f.D.X().experiments.B("autoplay_time")||1E4},W_=function(f,k){k=GSn(f,k);
var G=Math,t=G.min;var Z=(0,g.S)()-f.V;G=t.call(G,Z,k);k=k===0?1:Math.min(G/k,1);f.VG.setAttribute("stroke-dashoffset",`${-211*(k+1)}`);k>=1&&f.B()&&!f.isCasting()?f.select(!0):f.B()&&f.K.start()},GSn=function(f,k){return k?k:f.api.isFullscreen()?(f=f.api.getVideoData().l6,f===-1||f===void 0?8E3:f):f.api.Gx()>=0?f.api.Gx():f.api.X().experiments.B("autoplay_time")||1E4},DS=function(f){return g.pz(f.player)&&f.C()&&!f.S},Vx=function(f){var k=f.q_();
k!==f.O&&(f.O=k,f.player.publish("autonavvisibility"))},v_=function(f){return g.pz(f.player)&&f.C()&&!f.Z},B_=function(f){var k=f.q_();
k!==f.S6&&(f.S6=k,f.player.publish("autonavvisibility"))},t3p=function(f){f=f.X();
return f.Rp&&!f.disableOrganicUi},Zte=function(f){var k=f.player.getVideoData();
if(!k||f.B===k.Bc)return!1;f.B=k.Bc;return!0},uBW=function(f){f.player.yP("endscreen");
var k=f.player.getVideoData();k=new g.hg(Math.max((k.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var G=new g.hg(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});f.player.wO([k,G])};
g.oj.prototype.Gx=g.ua(15,function(){return this.app.Gx()});
g.p3.prototype.Gx=g.ua(14,function(){return this.getVideoData().dG});
g.hj.prototype.zJ=g.ua(13,function(f){this.ew().zJ(f)});
g.X4.prototype.zJ=g.ua(12,function(f){this.Lu!==f&&(this.Lu=f,this.xK())});
var jq=class extends g.J{constructor(f){super({G:"div",j:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.Ky=void 0;this.V=0;f.Y("web_post_play_autonav_embiggening")&&g.bD(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.J({G:"div",j:"ytp-autonav-endscreen-countdown-container"});g.w(this,this.container);this.container.mx(this.element);var k=f.X(),G=k.S;this.D=f;this.suggestion=null;this.onVideoDataChange("newdata",this.D.getVideoData());this.U(f,"videodatachange",
this.onVideoDataChange);this.K=new g.J({G:"div",j:"ytp-autonav-endscreen-upnext-container",J:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},L:[{G:"div",j:"ytp-autonav-endscreen-topbar-container",L:[{G:"div",j:"ytp-autonav-endscreen-upnext-header"},{G:"div",j:"ytp-autonav-endscreen-upnext-alternative-header",zB:"{{autoplayAlternativeHeader}}"}]},{G:"a",j:"ytp-autonav-endscreen-link-container",
J:{href:"{{url}}",target:G?k.S6:""},L:[{G:"div",j:"ytp-autonav-endscreen-upnext-thumbnail",J:{style:"{{background}}"},L:[{G:"div",J:{"aria-label":"{{timestamp}}"},TB:["ytp-autonav-timestamp"],zB:"{{duration}}"},{G:"div",TB:["ytp-autonav-live-stamp"],zB:"Live"},{G:"div",TB:["ytp-autonav-upcoming-stamp"],zB:"Upcoming"}]},{G:"div",j:"ytp-autonav-endscreen-video-info",L:[{G:"div",j:"ytp-autonav-endscreen-premium-badge"},{G:"div",j:"ytp-autonav-endscreen-upnext-title",zB:"{{title}}"},{G:"div",j:"ytp-autonav-endscreen-upnext-author",
zB:"{{author}}"},{G:"div",j:"ytp-autonav-view-and-date",zB:"{{views_and_publish_time}}"},{G:"div",j:"ytp-autonav-author-and-view",zB:"{{author_and_views}}"}]}]}]});g.w(this,this.K);this.K.mx(this.container.element);G||this.U(this.K.At("ytp-autonav-endscreen-link-container"),"click",this.Do);this.D.createClientVe(this.container.element,this,115127);this.D.createClientVe(this.K.At("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.J({G:"button",j:"ytp-autonav-endscreen-upnext-header-close-button",
J:{"aria-label":"Cancel autoplay"}});g.w(this,this.closeButton);f.Y("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.kj,this),this.D.createClientVe(this.closeButton.element,this,115129),this.K.At("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.J({G:"div",j:"ytp-autonav-overlay"});g.w(this,this.overlay);this.overlay.mx(this.container.element);this.A=new g.J({G:"div",j:"ytp-autonav-endscreen-button-container"});g.w(this,
this.A);this.A.mx(this.container.element);this.cancelButton=new g.J({G:"button",TB:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],J:{"aria-label":"Cancel autoplay"},zB:"Cancel"});g.w(this,this.cancelButton);this.cancelButton.mx(this.A.element);this.cancelButton.listen("click",this.kj,this);this.D.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.J({G:"a",TB:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],J:{href:"{{url}}",role:"button","aria-label":"Play next video"},zB:"Play Now"});g.w(this,this.playButton);this.playButton.mx(this.A.element);this.playButton.listen("click",this.Do,this);this.D.createServerVe(this.playButton.element,this.playButton,!0);(k=this.D.getVideoData())&&kSY(this,k);this.C=new g.CW(()=>{hU(this)},500);
g.w(this,this.C);this.S6();this.U(f,"autonavvisibility",this.S6)}O(f){this.suggestion!==f&&(this.suggestion=f,g.nj(this.K,f),this.playButton.updateValue("url",this.suggestion.Sv()),og(this))}B(){return this.V>0}Z(){this.B()||(this.V=Date.now(),hU(this),J2n(this.D,ZS(this)),g.Mu(this.D.getRootNode(),"countdown-running",this.B()))}S(){this.W();hU(this);var f=this.K.At("ytp-autonav-endscreen-upnext-header");f&&g.N6(f,"Up next")}W(){this.B()&&(this.C.stop(),this.V=0)}select(f=!1){this.D.nextVideo(!1,
f);this.W()}Do(f){g.v2(f,this.D)&&(f.currentTarget===this.playButton.element?this.D.logClick(this.playButton.element):f.currentTarget===this.K.At("ytp-autonav-endscreen-link-container")&&(f=this.K.At("ytp-autonav-endscreen-link-container"),this.D.logVisibility(f,!0),this.D.logClick(f)),this.Ky?(g.$P(this.D,"innertubeCommand",this.Ky),this.W()):this.select())}kj(){this.D.logClick(this.cancelButton.element);g.H4(this.D,!0);this.cancelCommand&&g.$P(this.D,"innertubeCommand",this.cancelCommand)}onVideoDataChange(f,
k){kSY(this,k);this.cancelCommand=k.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}S6(){var f=this.D.q_();this.hy!==f&&this.Ne(f);og(this);this.D.logVisibility(this.container.element,f);this.D.logVisibility(this.cancelButton.element,f);this.D.logVisibility(this.K.At("ytp-autonav-endscreen-link-container"),f);this.D.logVisibility(this.playButton.element,f)}JR(f){return f.width<400||f.height<459}};var Na=class extends g.J{constructor(f,k){super({G:"div",TB:["html5-endscreen","ytp-player-content",k||"base-endscreen"]});this.created=!1;this.player=f}create(){this.created=!0}destroy(){this.created=!1}C(){return!1}q_(){return!1}Ky(){return!1}};var hQs=class extends g.J{constructor(f){super({G:"div",TB:["ytp-upnext","ytp-player-content"],J:{"aria-label":"{{aria_label}}"},L:[{G:"div",j:"ytp-cued-thumbnail-overlay-image",J:{style:"{{background}}"}},{G:"span",j:"ytp-upnext-top",L:[{G:"span",j:"ytp-upnext-header",zB:"Up Next"},{G:"span",j:"ytp-upnext-title",zB:"{{title}}"},{G:"span",j:"ytp-upnext-author",zB:"{{author}}"}]},{G:"a",j:"ytp-upnext-autoplay-icon",J:{role:"button",href:"{{url}}","aria-label":"Play next video"},L:[{G:"svg",J:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},L:[{G:"circle",j:"ytp-svg-autoplay-circle",J:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",j:"ytp-svg-autoplay-ring",J:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",j:"ytp-svg-fill",J:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",j:"ytp-upnext-bottom",L:[{G:"span",j:"ytp-upnext-cancel"},
{G:"span",j:"ytp-upnext-paused",zB:"Autoplay is paused"}]}]});this.api=f;this.cancelButton=null;this.VG=this.At("ytp-svg-autoplay-ring");this.C=this.notification=this.K=this.suggestion=null;this.Ky=new g.CW(this.A,5E3,this);this.V=0;var k=this.At("ytp-upnext-cancel");this.cancelButton=new g.J({G:"button",TB:["ytp-upnext-cancel-button","ytp-button"],J:{tabindex:"0","aria-label":"Cancel autoplay"},zB:"Cancel"});g.w(this,this.cancelButton);this.cancelButton.listen("click",this.kj,this);this.cancelButton.mx(k);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.w(this,this.Ky);this.api.createClientVe(this.element,this,18788);k=this.At("ytp-upnext-autoplay-icon");this.U(k,"click",this.Do);this.api.createClientVe(k,this,115130);this.S6();this.U(f,"autonavvisibility",this.S6);this.U(f,"mdxnowautoplaying",this.ME);this.U(f,"mdxautoplaycanceled",this.Yj);g.Mu(this.element,"ytp-upnext-mobile",this.api.X().W)}A(){this.notification&&(this.Ky.stop(),this.jd(this.C),this.C=null,this.notification.close(),
this.notification=null)}O(f){this.suggestion=f;g.nj(this,f,"hqdefault.jpg")}S6(){this.Ne(this.api.q_());this.api.logVisibility(this.element,this.api.q_());this.api.logVisibility(this.At("ytp-upnext-autoplay-icon"),this.api.q_());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.q_())}FL(){window.focus();this.A()}Z(f){this.B()||(g.g_("a11y-announce",`Up Next ${this.suggestion.title}`),this.V=(0,g.S)(),this.K=new g.CW(()=>{W_(this,f)},25),W_(this,f),J2n(this.api,GSn(this,
f)));
g.ai(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}B(){return!!this.K}isCasting(){return this.api.getPresentingPlayerType()===3}S(){this.W();this.V=(0,g.S)();W_(this);g.bD(this.element,"ytp-upnext-autoplay-paused")}W(){this.B()&&(this.K.dispose(),this.K=null)}select(f=!1){if(this.api.X().Y("autonav_notifications")&&f&&window.Notification&&typeof document.hasFocus==="function"){let k=Notification.permission;k==="default"?Notification.requestPermission():k!=="granted"||document.hasFocus()||
(this.A(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.xG()}),this.C=this.U(this.notification,"click",this.FL),this.Ky.start())}this.W();this.api.nextVideo(!1,f)}Do(f){!g.j8(this.cancelButton.element,f.target)&&g.v2(f,this.api)&&(this.api.q_()&&this.api.logClick(this.At("ytp-upnext-autoplay-icon")),this.select())}kj(){this.api.q_()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.H4(this.api,!0)}ME(f){this.isCasting();this.show();
this.Z(f)}Yj(){this.isCasting();this.W();this.hide()}GB(){this.W();this.A();super.GB()}};var ois=class extends Na{constructor(f){super(f,"videowall-endscreen");this.D=f;this.stills=[];this.S=this.videoData=null;this.Z=this.O=!1;this.S6=null;g.bD(this.element,"modern-videowall-endscreen");this.K=new g.Vq(this);g.w(this,this.K);this.A=new g.CW(()=>{g.bD(this.element,"ytp-show-tiles")},0);
g.w(this,this.A);this.table=new g.Ky({G:"div",j:"ytp-modern-endscreen-content"});g.w(this,this.table);this.table.mx(this.element);f.getVideoData().Bc?this.B=new jq(f):this.B=new hQs(f);g.w(this,this.B);g.c4(this.player,this.B.element,4);f.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var f=this.player.getVideoData();f&&(this.videoData=f);this.W();this.K.U(this.player,"appresize",this.W);this.K.U(this.player,"onVideoAreaChange",this.W);this.K.U(this.player,"videodatachange",
this.onVideoDataChange);this.K.U(this.player,"autonavchange",this.V);this.K.U(this.player,"onAutonavCancelled",this.kj);f=this.videoData.autonavState;f!==this.S6&&this.V(f,!1);this.K.U(this.element,"transitionend",this.Do)}destroy(){this.K.K();g.Qo(this.stills);this.stills=[];super.destroy();g.ai(this.element,"ytp-show-tiles");this.A.stop();this.S6=this.videoData.autonavState}C(){return this.videoData?.Bv||this.videoData.autonavState!==1}show(){var f=this.hy;super.show();g.ai(this.element,"ytp-show-tiles");
this.player.X().W?g.mh(this.A):this.A.start();(this.Z||this.S&&this.S!==this.videoData.clientPlaybackNonce)&&g.H4(this.player,!1);DS(this)?(Vx(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||fRM(this.player.gy())&&this.player.Y("web_player_pip_logging_fix")?this.B.select(!0):this.B.Z():this.videoData.autonavState===3&&this.B.S()):(g.H4(this.player,!0),Vx(this));f!==this.hy&&this.player.logVisibility(this.element,!0)}hide(){var f=this.hy;super.hide();this.B.S();Vx(this);
f!==this.hy&&this.player.logVisibility(this.element,!1)}Do(f){f.target===this.element&&this.W()}W(){var f=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.C()];if(f.length){var k=this.D.l1(!0,this.D.isFullscreen()),G=Math.floor((k.width-64+16)/(g.$D(k.width*.27,250,450)+16));k=Math.min(3,Math.floor((k.height-64)/((k.width-64-(G-1)*16)/G*.5625+70)));g.rE(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.bD(this.element,`ytp-modern-endscreen-limit-rows-${k}`);g.Mu(this.element,"ytp-modern-endscreen-single-item",G===1);g.Mu(this.element,"ytp-modern-endscreen-row-0",k===0);G=this.table.element;G.ariaLive="polite";this.B.O(this.videoData.C());this.B instanceof jq&&og(this.B);g.Mu(this.element,"ytp-endscreen-takeover",DS(this));Vx(this);k=0;G.ariaBusy="true";var t=f.length;for(let Z=0;Z<t;Z++){let u=Z%t,h=this.stills[Z];h||(h=new g.Vha(this.player),this.stills[Z]=h,G.appendChild(h.element));g.J6c(h,
f[u]);k++}this.stills.length=k}}onVideoDataChange(){var f=this.player.getVideoData({playerType:1});this.videoData!==f&&(f?.C()?(this.videoData=f,this.W()):this.player.Wz("missg",{vid:f?.videoId||"",cpn:f?.clientPlaybackNonce||""}))}Ky(){return this.B.B()}V(f,k=!1){var G=this.videoData?.Bv;if(f===1){if(!G||k)this.Z=!1,this.S=this.videoData.clientPlaybackNonce;this.B.W();this.hy&&this.W()}else this.Z=!0,this.hy&&DS(this)&&(f===2?this.B.Z():f===3&&this.B.S())}kj(f){if(f){for(f=0;f<this.stills.length;f++)this.D.logVisibility(this.stills[f].element,
!0);this.V(1,!0)}else this.S=null,this.Z=!1;this.W()}q_(){return this.hy&&DS(this)}};var WKn=class extends g.J{constructor(f){var k=f.X(),G=g.ln||g.zf?{style:"will-change: opacity"}:void 0,t=k.S,Z=["ytp-videowall-still"];k.W&&Z.push("ytp-videowall-show-text");super({G:"a",TB:Z,J:{href:"{{url}}",target:t?k.S6:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{G:"div",j:"ytp-videowall-still-image",J:{style:"{{background}}"}},{G:"span",j:"ytp-videowall-still-info",J:{"aria-hidden":"true"},L:[{G:"span",j:"ytp-videowall-still-info-bg",
L:[{G:"span",j:"ytp-videowall-still-info-content",J:G,L:[{G:"span",j:"ytp-videowall-still-info-title",zB:"{{title}}"},{G:"span",j:"ytp-videowall-still-info-author",zB:"{{author_and_views}}"},{G:"span",j:"ytp-videowall-still-info-live",zB:"Live"},{G:"span",j:"ytp-videowall-still-info-duration",zB:"{{duration}}"}]}]}]},{G:"span",TB:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},L:[{G:"span",j:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",
j:"ytp-videowall-still-listlabel-length",L:[" (",{G:"span",zB:"{{playlist_length}}"},")"]}]},{G:"span",TB:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:{"aria-hidden":"true"},L:[{G:"span",j:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",j:"ytp-videowall-still-listlabel-length",zB:" (50+)"}]}]});this.suggestion=null;this.K=t;this.api=f;this.B=new g.Vq(this);g.w(this,this.B);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.B.U(f,"videodatachange",
this.onVideoDataChange);f.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.rz(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.SE||void 0)&&this.api.logClick(this.element)}onClick(f){if(g.XB(this.api.X())&&this.api.Y("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let k=this.suggestion.Sv(),G={};g.TP(this.api,G);k=g.Sh(k,G);g.B2(k,this.api,f)}else g.v2(f,this.api,
this.K,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(f){switch(f.keyCode){case 13:case 32:f.defaultPrevented||(this.select(),f.preventDefault())}}onVideoDataChange(){var f=this.api.getVideoData(),k=this.api.X();this.K=f.Hr?!1:k.S}};var DZp=class extends Na{constructor(f){super(f,"videowall-endscreen");this.D=f;this.S=0;this.stills=[];this.Z=this.videoData=null;this.A=this.S6=!1;this.kj=null;this.W=new g.Vq(this);g.w(this,this.W);this.V=new g.CW(()=>{g.bD(this.element,"ytp-show-tiles")},0);
g.w(this,this.V);var k=new g.J({G:"button",TB:["ytp-button","ytp-endscreen-previous"],J:{"aria-label":"Previous"},L:[g.uX()]});g.w(this,k);k.mx(this.element);k.listen("click",this.ME,this);this.table=new g.Ky({G:"div",j:"ytp-endscreen-content"});g.w(this,this.table);this.table.mx(this.element);k=new g.J({G:"button",TB:["ytp-button","ytp-endscreen-next"],J:{"aria-label":"Next"},L:[g.hy()]});g.w(this,k);k.mx(this.element);k.listen("click",this.VG,this);f.getVideoData().Bc?this.B=new jq(f):this.B=new hQs(f);
g.w(this,this.B);g.c4(this.player,this.B.element,4);f.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var f=this.player.getVideoData();f&&(this.videoData=f);this.K();this.W.U(this.player,"appresize",this.K);this.W.U(this.player,"onVideoAreaChange",this.K);this.W.U(this.player,"videodatachange",this.onVideoDataChange);this.W.U(this.player,"autonavchange",this.O);this.W.U(this.player,"onAutonavCancelled",this.Do);f=this.videoData.autonavState;f!==this.kj&&this.O(f,!1);this.W.U(this.element,
"transitionend",this.Yj)}destroy(){this.W.K();g.Qo(this.stills);this.stills=[];super.destroy();g.ai(this.element,"ytp-show-tiles");this.V.stop();this.kj=this.videoData.autonavState}C(){return this.videoData?.Bv||this.videoData?.autonavState!==1}show(){var f=this.hy;super.show();g.ai(this.element,"ytp-show-tiles");this.player.X().W?g.mh(this.V):this.V.start();(this.A||this.Z&&this.Z!==this.videoData.clientPlaybackNonce)&&g.H4(this.player,!1);v_(this)?(B_(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||fRM(this.player.gy())&&this.player.Y("web_player_pip_logging_fix")?this.B.select(!0):this.B.Z():this.videoData.autonavState===3&&this.B.S()):(g.H4(this.player,!0),B_(this));f!==this.hy&&this.player.logVisibility(this.element,!0)}hide(){var f=this.hy;super.hide();this.B.S();B_(this);f!==this.hy&&this.player.logVisibility(this.element,!1)}Yj(f){f.target===this.element&&this.K()}K(){var f=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.C()];if(f.length){g.bD(this.element,
"ytp-endscreen-paginate");var k=this.D.l1(!0,this.D.isFullscreen()),G=g.dJ(this.D);G&&(G=G.Mz()?48:32,k.width-=G*2);var t=k.width/k.height,Z=96/54,u=G=2,h=Math.max(k.width/96,2),W=Math.max(k.height/54,2),D=f.length;var V=D*4;for(V-=4;V>0&&(G<h||u<W);){var U=G/2,e=u/2,q=G<=h-2&&V>=e*4,O=u<=W-2&&V>=U*4;if((U+1)/e*Z/t>t/(U/(e+1)*Z)&&O)V-=U*4,u+=2;else if(q)V-=e*4,G+=2;else if(O)V-=U*4,u+=2;else break}Z=!1;V>=12&&D*4-V<=6&&(u>=4||G>=4)&&(Z=!0);V=G*96;h=u*54;t=V/h<t?k.height/h:k.width/V;t=Math.min(t,2);
V=Math.floor(Math.min(k.width,V*t));h=Math.floor(Math.min(k.height,h*t));k=this.table.element;k.ariaLive="polite";g.uR(k,V,h);g.X3(k,{marginLeft:`${V/-2}px`,marginTop:`${h/-2}px`});this.B.O(this.videoData.C());this.B instanceof jq&&og(this.B);g.Mu(this.element,"ytp-endscreen-takeover",v_(this));B_(this);V+=4;h+=4;t=0;k.ariaBusy="true";for(W=0;W<G;W++)for(U=0;U<u;U++)if(q=t,O=0,Z&&W>=G-2&&U>=u-2?O=1:U%2===0&&W%2===0&&(U<2&&W<2?U===0&&W===0&&(O=2):O=2),q=g.zx(q+this.S,D),O!==0){e=this.stills[t];e||
(e=new WKn(this.player),this.stills[t]=e,k.appendChild(e.element));var F=Math.floor(h*U/u);let m=Math.floor(V*W/G),a=Math.floor(h*(U+O)/u)-F-4,r=Math.floor(V*(W+O)/G)-m-4;g.YZ(e.element,m,F);g.uR(e.element,r,a);g.X3(e.element,"transitionDelay",(U+W)/20+"s");g.Mu(e.element,"ytp-videowall-still-mini",O===1);g.Mu(e.element,"ytp-videowall-still-large",O>2);O=Math.max(r,a);g.Mu(e.element,"ytp-videowall-still-round-large",O>=256);g.Mu(e.element,"ytp-videowall-still-round-medium",O>96&&O<256);g.Mu(e.element,
"ytp-videowall-still-round-small",O<=96);q=f[q];e.suggestion!==q&&(e.suggestion=q,O=e.api.X(),F=g.sK(e.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.nj(e,q,F),g.XB(O)&&!e.api.Y("web_player_log_click_before_generating_ve_conversion_params")&&(O=q.Sv(),F={},g.EA(e.api,"addEmbedsConversionTrackingParams",[F]),O=g.Sh(O,F),e.updateValue("url",O)),(q=(q=q.sessionData)&&q.itct)&&e.api.setTrackingParams(e.element,q));t++}k.ariaBusy="false";g.Mu(this.element,"ytp-endscreen-paginate",
t<D);for(f=this.stills.length-1;f>=t;f--)G=this.stills[f],g.BS(G.element),g.P0(G);this.stills.length=t}}onVideoDataChange(){var f=this.player.getVideoData({playerType:1});this.videoData!==f&&(f?.C()?(this.S=0,this.videoData=f,this.K()):this.player.Wz("missg",{vid:f?.videoId||"",cpn:f?.clientPlaybackNonce||""}))}VG(){this.S+=this.stills.length;this.K()}ME(){this.S-=this.stills.length;this.K()}Ky(){return this.B.B()}O(f,k=!1){var G=this.videoData?.Bv;if(f===1){if(!G||k)this.A=!1,this.Z=this.videoData.clientPlaybackNonce;
this.B.W();this.hy&&this.K()}else this.A=!0,this.hy&&v_(this)&&(f===2?this.B.Z():f===3&&this.B.S())}Do(f){if(f){for(f=0;f<this.stills.length;f++)this.D.logVisibility(this.stills[f].element,!0);this.O(1,!0)}else this.Z=null,this.A=!1;this.K()}q_(){return this.hy&&v_(this)}};var V3Y=class extends g.J{constructor(f){super({G:"button",TB:["ytp-watch-on-youtube-button","ytp-button"],zB:"{{content}}"});this.D=f;this.buttonType=this.buttonType=1;this.B();this.buttonType===2&&g.bD(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.B);this.Ne(!0)}B(){switch(this.buttonType){case 1:var f="Watch again on YouTube";var k=156915;break;case 2:f="Continue watching on YouTube";k=156942;break;default:f="Continue watching on YouTube",
k=156942}this.update({content:f});this.D.hasVe(this.element)&&this.D.destroyVe(this.element);this.D.createClientVe(this.element,this,k)}onClick(f){this.D.Y("web_player_log_click_before_generating_ve_conversion_params")&&this.D.logClick(this.element);g.B2(this.getVideoUrl(),this.D,f);this.D.Y("web_player_log_click_before_generating_ve_conversion_params")||this.D.logClick(this.element)}getVideoUrl(){var f=!0;switch(this.buttonType){case 1:f=!0;break;case 2:f=!1}f=this.D.getVideoUrl(f,!1,!1,!0);var k=
this.D.X();if(g.XB(k)){let G={};g.XB(k)&&g.EA(this.D,"addEmbedsConversionTrackingParams",[G]);f=g.Sh(f,G)}return f}logVisibility(){this.D.logVisibility(this.element,this.hy&&this.Zo)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}FK(f){super.FK(f);this.logVisibility()}};var viC=class extends Na{constructor(f){super(f,"watch-again-on-youtube-endscreen");this.watchButton=new V3Y(f);g.w(this,this.watchButton);this.watchButton.mx(this.element);g.f26(f)&&(this.B=new g.pbb(f),g.w(this,this.B),this.K=new g.J({G:"div",TB:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],J:{tabIndex:"-1"},L:[this.B]}),g.w(this,this.K),this.B.mx(this.K.element),this.K.mx(this.element));f.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.B?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let k=this.K;if(k){var f=this.B.hasSuggestions();g.Mu(this.element,"ytp-shorts-branded-ui",f);f?k.show():k.hide()}g.dJ(this.player)?.zJ(!0);this.player.logVisibility(this.element,!0);this.watchButton.FK(!0)}}hide(){super.hide();g.dJ(this.player)?.zJ(!1);this.player.logVisibility(this.element,!1);this.watchButton.FK(!1)}};g.S6("endscreen",class extends g.my{constructor(f){super(f);this.endScreen=null;this.B=this.K=!1;this.listeners=new g.Vq(this);g.w(this,this.listeners);var k=f.X();f.isEmbedsShortsMode()?this.endScreen=new viC(f):t3p(f)?(this.K=!0,Zte(this),k.Y("delhi_modern_endscreen")?this.endScreen=new ois(f):this.endScreen=new DZp(f)):this.endScreen=new Na(f);g.w(this,this.endScreen);g.c4(f,this.endScreen.element,4);uBW(this);this.listeners.U(f,"videodatachange",this.onVideoDataChange,this);this.listeners.U(f,
g.tp("endscreen"),G=>{this.onCueRangeEnter(G)});
this.listeners.U(f,g.Z5("endscreen"),G=>{this.onCueRangeExit(G)})}ZY(){var f=this.player.getVideoData(),k=f.mutedAutoplay&&(f.limitedPlaybackDurationInSeconds>0||f.endSeconds>0||f.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!k)return!0;var G=!(!f.C()&&!f.suggestions?.length);G=!t3p(this.player)||G;var t=f.yu,Z=this.player.g$();return(G||!!f?.Bv)&&!t&&!Z&&!k}q_(){return this.endScreen.q_()}GF(){return this.q_()?this.endScreen.Ky():!1}GB(){this.player.yP("endscreen");super.GB()}load(){{let G=this.player.getVideoData(),t=G.transitionEndpointAtEndOfStream;if(t&&t.videoId){var f=this.player.aG().QB.get("heartbeat");var k=G.C();!k||t.videoId!==k.videoId||G.Vi?(this.player.rz(t.videoId,
void 0,void 0,!0,!0,t),f&&f.NN("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),f=!0):f=!1}else f=!1}f||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(f){this.ZY()&&(this.endScreen.created||this.endScreen.create(),f.getId()==="load"&&this.load())}onCueRangeExit(f){f.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){uBW(this);this.K&&Zte(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new DZp(this.player),g.w(this,this.endScreen),g.c4(this.player,this.endScreen.element,4))}});})(_yt_player);
